### ISSUE TITLE
Mentorship program announcement 

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#10]
Hello,

The text below will be submitted as an issue to the nodejs/node project to announce the mentorship program and open the door for enrollment. Please read it and provide feedback before having it submitted. CC @nodejs/community-committee @nodejs/tsc 

follow the link to see the issue content in a gist: https://gist.github.com/Bamieh/b87fb3f279665966dec86f35a741c8d9

<details><summary>OR Click here to see a copy of the gist</summary>
<p>

Hello dears! 🦌 

I am glad to announce the start of the enrollment process of the **Node.js Mentorship program**.

## General overview

The goal is simple. Getting more people to contribute to Node.js and to help evolve the Node.js ecosystem by providing general help for all Node.js users.

> To bring more contributors to Node.js projects by mentoring people about the Node.js environment and ecosystem, helping them contribute to Node.js, championing their PRs through code review, and giving general help.

The mentorship program duration is 6 months. The matched mentor/mentee pair will agree on specific goals to reach during this duration. The program will be super beneficial and rewarding to both the mentors and mentees.

Please have a quick look at the mentorship repo for the full details:
https://github.com/nodejs/mentorship

## How can I help?

It would be awesome to have you enrolled in the mentorship program, either as a mentor or a mentee.

_Joining this program will help in driving the Node.js open-source project forward by bringing more contributors to the project, increasing confidence in using Node.js, and making more Node.js experts!_

### For Mentors

Mentors play a huge role in defining the mentee's experience with Node.js. You must have some kind of contribution to any project under the Node.js umbrella to become a mentor.

Mentors provide general guidance and resources for their mentees to answer their questions. You do not need to know everything to be a mentor. Simply guiding your mentee to the right resources is enough.

Fill in this form to enroll as a mentor: https://goo.gl/forms/O6VX4ZglvCfX94vu2

### For Mentees

You can enroll as a mentee whether you are new to Node.js or you want to get tailored guidance for a specific goal you have in mind.

If you are interested in contributing to Node.js, learning more about the core Node.js project, or you're interested in need general guidance around Node.js. The mentorship program is a great starting point!

Fill in this form to enroll as a mentee: https://goo.gl/forms/TUEAIYVqoFXA4WpF2

## When did this happen?

The mentorship program started as an initiative under the Node.js Community Committee. You can get more in context by starting here: https://github.com/nodejs/community-committee/issues/172

You are awesome, and we'd love to have you!

Cheers!

</p>
</details>

**Comment by mhdawson** [comment]
Great to see us getting to the point were we can start bringing people into the mentorship program.

**Comment by bnb** [comment]
I've reached out to @gtewallace to see if we can get those Google Forms under a Node.js Foundation account 🤗

**Comment by Bamieh** [comment]
@bnb awesome thanks!

**Comment by ralphtheninja** [comment]
I signed up as a mentee :smile:

**Comment by mcollina** [comment]
This is fantastic. Good job!!

**Comment by MylesBorins** [comment]
I noticed the code of conduct link points to the mentorship repo, which in
turn directs people to the admin repo. Would it perhaps make sense to
simply link to the admin repo?

**Comment by Bamieh** [comment]
@MylesBorins it might make more sense I'm not actually sure. But it has an additional text about confidentiality of mentors and mentees.

**Comment by flickz** [comment]
@Bamieh Free to sign up as mentee now?

**Comment by Bamieh** [comment]
Hey @flickz! The application forms are opened now, please follow the links in the main repo README to apply and get all the details about the program! Hope see you soon!

**Comment by BeniCheni** [comment]
Hi, kudos to this awesome program! Read all excellent details and signed up as a mentee. Congrats to the program and hope to be considered as a mentee. 😄

**Comment by Bamieh** [comment]
@BeniCheni Thanks for the feedback! We'd love to have you.

**Comment by danielryanbeck** [comment]
This whole thing is incredible. The kind of thing you hope would happen but doesn't often come along.  Hoping we all unwrap a golden ticket!

**Comment by PrajwalM2212** [comment]
@Bamieh How many hours is the mentee expected to commit towards the program on a daily basis ?

**Comment by ankibalyan** [comment]
This is great! Happy to be here! Thanks for keeping the program focused. Kudos to the node team!

**Comment by Bamieh** [comment]
@ankibalyan Thank you!

**Comment by Bamieh** [comment]
@PrajwalM2212 this should be coordinated with your match based on the goals you've set, however the program expects a minimum amount of meetings between the pair, and commitment to update the "mentorship bio" to report meetings and milestones. In order to graduate successfully from the program you need to have reached your mentorship goals, or parts of it at least.

**Comment by PrajwalM2212** [comment]
@Bamieh  I have applied as a mentee clearly addressing my goals and experiences. Thanks to the organisation for such a great and generous program.

**Comment by PrajwalM2212** [comment]
@Bamieh  I have a few questions 
Has the program already started ? 
How long should I wait before getting accepted ?

**Comment by Bamieh** [comment]
@PrajwalM2212 Thanks for your interest and support! we're currently in the first round which will end in September, after that we'll announce a new round.

The mentor/mentee ratio is super skewed so getting everyone applied to join might take a while. Our plan however is to increase the mentoring capacity gradually with time

**Comment by sladyn98** [comment]
@Bamieh I applied to the mentorship program. How long should i wait before getting accepted?
Thanks for your time.

**Comment by madguy02** [comment]
Hi everyone, I have applied for the Node mentorship program (as a mentee) . Really looking forward to be part of the foundation. :D

**Comment by Hamza-324** [comment]
Hello Everybody, Do we have a date on when the mentorship program is supposed to start this year?

**Comment by Bamieh** [comment]
@Hamza-324 The matching process is estimated so start on June 10th. The application form is open for mentees to apply. You can find it on the first line of the README in this repo.

**Comment by Bamieh** [comment]
Closing this issue as per @amiller-gh's recommendation to avoid confusion.
