### ISSUE TITLE
A friendlier README for the mentorship repo

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#100]
I believe that a few friendly illustrations on the main README will make the mentorship program more welcoming and friendlier to new comers.

- An above the fold illustration about the goal of mentorship and the benefits.

- Another illustration might be for the mindset and relationship of mentees and mentors.

- Finally, the current diagram for the mentorship process is very rigid, it would be nice to have that completely replaced as well.

**Comment by princiya** [comment]
@Bamieh tried to illustrate something :)

![node mentorship full_1](https://user-images.githubusercontent.com/8022693/46906126-de379600-cefe-11e8-819b-c94e919e7ba7.jpg)

**Comment by Bamieh** [comment]
@princiya 	haha I love it! Thank you so much 🤗

CC @nodejs/mentorship

**Comment by dshaw** [comment]
@princiya wonderful!

**Comment by JayDevelopment** [comment]
Thanks! I applied for the mentorship program awhile ago; do you know when I should expect to be contacted?
