### ISSUE TITLE
Add '.md' Extension to the 9-22-2018 Meeting Note.

### ISSUE THREAD

**Issue by segunadeleye** [nodejs/mentorship#101]
The meeting note https://github.com/nodejs/mentorship/blob/master/meeting/9-22-2018 does not have the '.md' extension so it is not formatted.

**Comment by segunadeleye** [comment]
I would like to work on this.

**Comment by segunadeleye** [comment]
I created a pull request for this issue. You can find it here https://github.com/nodejs/mentorship/pull/102

**Comment by Bamieh** [comment]
@segunadeleye merged, thank you @segunadeleye .
