### ISSUE TITLE
Want to attend a meeting, but the time doesn't work for me :(

### ISSUE THREAD

**Issue by mjordancodes** [nodejs/mentorship#103]
Spoke with @dshaw a bunch over the past few days at Node + JS Interactive. I am very interested in working with the mentorship team, but the meeting time (9am PST) doesn't work with my job schedule. Dan said that time could potentially be flexible. I'm an instructor and lecturing daily (Monday - Friday) from 9am-12pm. Outside of that my schedule is much more flexible and I would be able to attend meetings. 

Part of my job as an instructor is working with students to help them build projects after graduation while on the job hunt. I want to point them to fun open source projects that have good communities. I'd like to figure out a way to bring the mentorship program to the students I work with in a sustainable way. (Each new round of grads could be mentored by the previous group). I'm also interested in how to make this program work and be sustainable outside of the school I work at. Would love to learn more about what this group is doing and how I can help :)

**Comment by davidguttman** [comment]
Sorry nobody got back to you on this! We're actively working on the mentorship program, and we'll try to do a much better job of letting people know how to get involved in the future!
