### ISSUE TITLE
communication channel for the matched mentor/mentee 's first meeting

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#11]
According to the [mentorship process](https://github.com/nodejs/mentorship#process). The matched mentor and mentee will have a [kickoff meeting](https://github.com/nodejs/mentorship#kickoff) with one of the mentorship program members to agree on several things:

> A meeting will be scheduled to introduce them to each other. Pairs should agree on a mentorship schedule, expectations and goals, and the medium of communication. They should also decide on what should be held confidential and what can be shared outside the relationship. 

This meeting (and possibly future individual meetings afterwards between the matched pair) needs a *communication channel*.

Requirements:
- Optional video call
- chat
- 3 way communication channel (for mentor/mentee/and a member in the mentorship program).

Possible options:
- Slack
- Google hangouts
- Zoom.us
- IRCcloud

Personally I find any of those options great (except the IRC i personally don't like it). Let us agree on one official way for those meetings. CC @nodejs/tsc @nodejs/community-committee

**Comment by Bamieh** [comment]
@mhdawson  or @bnb can we add this to the next meeting's agenda? Thanks! I created a `cc-agenda` label for this project.

**Comment by bnb** [comment]
@Bamieh yep! Always feel free to add agenda items 😁

**Comment by Bamieh** [comment]
@obensource suggested: https://talky.io/
@bnb suggested: https://appear.in/

We agreed to just choose a tool and start in the commcomm meeting. I'll post a comment soon with my choice to see if there is any feedback/objections on the chosen communication tool.

**Comment by Bamieh** [comment]
So, 2 weeks later, I tried so many tools and decided to go with slack.


talky and appear are not persistent, so although they serve as a good method for the first meeting, I want something that all parties can use consistently if they agree to and have it personalized to them (user accounts and a join process), instead of having to create a new meeting room every time etc.

IRC is way too primitive IMHO, it lacks a lot of features and it is intimidating for new users. Discord was a very good candidate, but i favored slack because discord is too gaming oriented.

**Comment by dshaw** [comment]
I suggested in https://github.com/nodejs/community-committee/issues/261 that we should use http://nodeslackers.com

**Comment by Bamieh** [comment]
as per @dshaw's suggestion, we agreed to go with nodeslackers ❤️
