### ISSUE TITLE
CommunityBridge for Mentorship

### ISSUE THREAD

**Issue by bnb** [nodejs/mentorship#117]
Hey y'all.

At the Linux Foundation Open-source Leadership Summit, [CommunityBridge](https://communitybridge.org/) was launched. In addition to OpenCollective-like funding, it provides mentorship tooling.

Wanted to raise this as an issue for y'all since it's a possible tool to help with mentorship 👍

**Comment by Bamieh** [comment]
@bnb thanks for sharing! Definitely worth checking.
