### ISSUE TITLE
[Mentor Bio] Matteo Collina

### ISSUE THREAD

**Issue by mcollina** [nodejs/mentorship#120]
Basic info | &nbsp;
-|-
Preferred mentoring format | 1:1, slack, twitter, emails
Mentoring scope | Node.js Streams
Background | Technical Director @NearForm, TSC member
Experience | 10+ years

### About me

Hey, everyone. I am Matteo Collina. I'm a Node.js old-timer and as such I'm maintaining streams and http. I'm also a member of the Technical Steering Committee. I'm a Technical Director at Nearform, and I'm also busy giving talks all around the world.

I'm looking for a mentee who is interested in improving their understanding of Node.js core, specifically in the streams and http areas. Those are critical areas in Node.js, and most people find solving node core bugs on streams and http very intimidating. I'd love to guide my mentee through all the pitfalls and solve some very hard bugs!

**Comment by tamalchowdhury** [comment]
Thanks for joining Matt. I'm looking into how web video streams work, that would be really helpful.

**Comment by ttbrijkishor** [comment]
Hi @mcollina, I wanted to join mentorship program for streams however form is closed. Is it possible to be part of your mentorship program? 
It would also helpful if your discussions are available those would very valuable information for learners like me. 
Thanks

**Comment by unstoo** [comment]
If you can take mantees no more, maybe you could publish materials?

**Comment by andreMc05** [comment]
Hello Matteo Collina,
First thing I would like to do is to thank you for offering you time to
mentor the Node community. Your deep understanding of not only Node
streaming, but also debugging and performance optimization is
irreplaceable. I know you are a very busy.

I love taking things apart just to see how they work. This is the mentality
that I use in my software development as well. So I am not afraid to dig
inside of the various API, libraries, and frameworks. This has taught me
much about how software is structured. I seek several of your talks and am
excited to dive into AutoCannon, 0x, Clinic.js, and Fastify.

I would to be your mentee.


Thank you much for your time,

Andre McGruder

**Comment by mcollina** [comment]
Hey @andreMc05, participation in the mentorship program in handled by the Node.js mentorship group. If you are interested in fastify, you might want to start tackling some of https://github.com/fastify/fastify/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22.
