### ISSUE TITLE
[Mentor Bio] Ujjwal Sharma

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/mentorship#122]
Basic info |  
-- | --
Preferred mentoring format | 1:1
Mentoring scope | VM, V8
Background | Independent OSS contributor
Experience | ~5 years

### About Me

Hello everyone! I am Ujjwal. I am one of the core collaborators and also one of the maintainers of Electron. Apart from that, I contribute as much as I can to the JavaScript ecosystem through V8 and TC39. When I'm not writing code, I'm traveling to different cities around the world talking about the stuff I've been working on.

One of the reasons I've come this far in OSS is because I stand on the shoulders of giants. People with years of experience building runtimes and compilers not only welcomed me with open arms, but taught me pretty much everything I'm proud of today. I plan to make someone else's journey into the JavaScript ecosystem better by passing on some of the experience and insight I have gained around the different areas of the codebase.

**Comment by tamalchowdhury** [comment]
Looking forward to learning from you Ujjwal!!

**Comment by venkatshukla** [comment]
Great to see you as part of this program. 👍 Looking forward to it!
