### ISSUE TITLE
When will next will the mentees application be opened?

### ISSUE THREAD

**Issue by ngfizzy** [nodejs/mentorship#125]
I tried applying to become a mentee through [this form](https://docs.google.com/forms/d/e/1FAIpQLSfYQhvBa5LwsDRyFYIULsPx2kAsiyAi_5C3eu07tp8joH2yeA/closedform) but it seems application has closed.

How long will it be before the next application window?

**Comment by Bamieh** [comment]
Hey @ngfizzy :wave:

We will announce the beginning of the new cohort it this Monday!

Actually, our plan was to announce it yesterday, but some delays were necessary.

**Comment by Tera99** [comment]
Hello! I am also interested. How can I stay updated and receive future announcements? Thanks in advance!

**Comment by Bamieh** [comment]
Hey @Tera99 That is a very good question, we should add it as a section in the README actually!

1. We'll be announcing it in the mentorship channel on slack. (node-js.slack.com via https://www.nodeslackers.com/)
2. We'll also announce it on twitter and other social platforms the foundation uses to announce things. (https://twitter.com/nodejs)
3. Github (this repo) is the source of truth for the program and we try to document everything here so we'll be updating the docs with all the info. (Star this repo)

**Comment by Tera99** [comment]
That sounds like a great first task for a beginner. Can I add that section to the README?

**Comment by Bamieh** [comment]
@Tera99 that would be great!
