### ISSUE TITLE
First Mentorship team meeting

### ISSUE THREAD

**Issue by dshaw** [nodejs/mentorship#13]
Now that we have a commitment from folks to join the team #12, let's meet.

I'd like to propose March 9th at 9am PT / noon ET / 7pm Palestine.

**Comment by Bamieh** [comment]
@dshaw Thanks for opening this issue and pushing things forward 😃 .
That would be 7pm my time, sounds good to me!

**Comment by dshaw** [comment]
Updated local time for @Bamieh. 🙏

**Comment by Bamieh** [comment]
@dshaw ahhh, i'm from **Palestine** not Pakistan 😄. anyways it might be useful to have this table for everyone (like we do in the commcomm meetings).

## Time
UTC Fri 09-March-2018 17:00 (05:00 PM):

Timezone | Date/Time
-- | --
US / Pacific | Fri 09-March-2018 09:00 (09:00 AM)
US / Mountain | Fri 09-March-2018 10:00 (10:00 AM)
US / Central | Fri 09-March-2018 11:00 (11:00 AM)
US / Eastern | Fri 09-March-2018 12:00 (12:00 PM)
London | Fri 09-March-2018 17:00 (05:00 PM)
Amsterdam | Fri 09-March-2018 18:00 (06:00 PM)
Moscow | Fri 09-March-2018 20:00 (08:00 PM)
Chennai | Fri 09-March-2018 22:30 (10:30 PM)
Hangzhou | Sat 10-March-2018 01:00 (01:00 AM)
Tokyo | Sat 10-March-2018 02:00 (02:00 AM)
Sydney | Sat 10-March-2018 04:00 (04:00 AM)

Or in your local time:

- https://www.timeanddate.com/worldclock/fixedtime.html?msg=First+Mentorship+Team+Meeting+2018-03-09&iso=20180309T17
- or http://www.wolframalpha.com/input/?i=05PM+UTC,+March+09,+2018+in+local+time

**Comment by dshaw** [comment]
@Bamieh Oh dear. My apologies. Thank you 🙏.

**Comment by dshaw** [comment]
@bnb @mhdawson Could you setup a Zoom meeting for this? Do you want to onboard me to be able to set this up?

**Comment by bnb** [comment]
@dshaw AFAIK the Zoom credentials are shared with the Foundation and are restricted as much as possible. I don't know if @mhdawson or I could make the call on that, but I also don't have an issue spinning up my machine to start meetings (especially if you don't mind if I don't participate if I have other obligations)  😬

**Comment by mhdawson** [comment]
I personally think we need to provide the credentials to the chairs of working groups in order to make it feasible.  @ZibbyKeaton any concern with that?

**Comment by ZibbyKeaton** [comment]
@mhdawson I think it makes sense to give zoom credentials to the chairs of the working groups - I would limit it to that, however. Only potential issue that I see is that we may have a limit on concurrent webinars, and the webinar feature is what allows you to stream to YouTube... I can research to see how we can resolve this problem, but in the meantime, maybe we just plan to not have any of these working group meetings happen at the same time. Sound good?

**Comment by mhdawson** [comment]
@ZibbyKeaton thanks, for the confirmation.  I'll share the credentials with Dan and then write up our policy of sharing with WG chairs.  I think the concurrency issue may already have been an issue with YouTube and I don't think we have any overlapping meetings yet. If we can find a solution that would be good.

**Comment by mhdawson** [comment]
@dshaw we are sharing the zoom credentials through lastpass. Can you create an account and then forward me the email used so I can try to share with you?

**Comment by dshaw** [comment]
@mhdawson Will do. Thank you.

**Comment by bnb** [comment]
I'll spin up today's meeting

**Comment by bnb** [comment]
Join link: https://zoom.us/j/656987750

**Comment by bnb** [comment]
Oops, posted the Modules Team Meeting link. Here's the correct one: https://zoom.us/j/659137458

**Comment by dshaw** [comment]
https://zoom.us/j/659137458

**Comment by bnb** [comment]
@dshaw nobody in that one?

**Comment by dshaw** [comment]
Notes from the first team meeting: https://docs.google.com/document/d/1L015QOGtabixPk64EAQQyU-W6bVbRdAne1ZU_uiskXk/edit#

Thank you, @Bamieh @hollomancer @bnb for joining.

**Comment by mhdawson** [comment]
I assume the notes will show up in github? As the google doc does not seem to be accessible.

**Comment by Bamieh** [comment]
@mhdawson yes yes! I will do that *very* soon!
