### ISSUE TITLE
The link to the signup form is placed very badly 

### ISSUE THREAD

**Issue by Ali-Khan5** [nodejs/mentorship#133]
The signup form link looks like its a reference link to  node-forward .You must clearly mention this in the end of the main readme about the signup link

**Comment by Bamieh** [comment]
Thanks for the feedback. The form was closed so we did not have it mentioned on the README file. Currently the second cohort is announced so the form is the first thing you see in the repo README. When the applications are closed, we should make that clear in the README as well.

I will close this. Please feel free to re-open :+1:
