### ISSUE TITLE
How can I submit as a mentee?

### ISSUE THREAD

**Issue by slim-hmidi** [nodejs/mentorship#134]
I submit for a long time as a mentee but I didn't receive any answer for the nodejs mentorship. Does this program starts or not because at the beginning I think that there is a session of mentors and organization. If the mentorship has already began, how can we participate?

**Comment by saulonunesdev** [comment]
Hi There, we are getting up with mentors and we will launch a new form on April 29 to pair up mentees and mentors.

**Comment by Bamieh** [comment]
Hello @slim-hmidi The application form has just been opened. Feel free to follow the link at the top of the repo README file to apply.
