### ISSUE TITLE
[Mentor Bio] Ben Michel

### ISSUE THREAD

**Issue by obensource** [nodejs/mentorship#135]
Basic info |  
-- | --
Preferred mentoring format | 1:1 or 1:n, any medium
Mentoring scope | Node.js General, Community Committee, i18n  
Background | Open Source Development, Product Development
Experience | Coding 7+ years, Some Mentoring

## About Me

Hi there, I'm Ben! 👋

I was first introduced to the Node.js community back in 2011, and it wasn't necessarily the tech that drew me into this insanely awesome project – it was the people. The incredibly driven, motivated, diverse set of people tackling deep issues in the web together with a myriad of tools they were inspired to write and discover the potential of.

In more recent years I've ramped up my involvement, and the community just continues to become more welcoming and incredible – all the time! 🙌

If you're interested in exploring some avenues that'll help you make your first few contributions to Node.js – whether it's in Node.js core, or getting involved in our community facing efforts (what our community committee drives) – let's connect! 🎉

I'd love to sync up with someone who cares deeply about the web and its community, and wants to wade deeper into the stream of contributing to its current problem space through JS and Node.js.

Some of my recent areas of involvement in Node.js have been:
* Community Committee
* i18n (internationalization)
* Website Redesign
* Core contributions – whenever I can.

Other things I'm interested in and have been getting more involved in:
* Bootstrapping the OpenJS Foundation
* ECMA 402 (JS Intl Library)
* W3C Audio Community Group (Web Audio API)

I'm interested in getting more involved in a core working group – like releases and/or modules. It would be fun to explore something like this together if that's your thing!

**Comment by arianadavis** [comment]
Hi Ben ( @obensource ) 👋, definitely excited to come across someone who is just as deeply passionate about the web as I am! Thanks for devoting your time to be apart of this amazing program. ⚡️

**Comment by RaviGambhire** [comment]
Hi Ben,
I am a node js developer and I want to contribute to this program.
I didn't find link for registration.where is it?

**Comment by Bamieh** [comment]
@RaviGambhire Registration for this round is closed. There are several ways to contribute to nodejs or mentorship. Please join us on slack for a chat on #mentorship channel
