### ISSUE TITLE
Clarification on questionnaire on the mentee form

### ISSUE THREAD

**Issue by madguy02** [nodejs/mentorship#141]
I have a confusion with this particular question mentioned below:

```
Are you willing to share your experience with the broader community, in what ways? *
Sharing knowledge is the essence of the mentorship program. Sharing your experience and knowledge about mentorship will help anyone in the community and those who did not get the opportunity to get matched this cohort. Resources may vary from videos, blog posts, issues, or even talks and sessions
```

As this is my first application to mentorship program (Node), i am not really sure of what kind of experience or knowledge should i share in this question. Help would be much appreciated

**Comment by Bamieh** [comment]
Hey @madguy02 👋 

We are looking for mentees who are willing to share what they learn and share their experience of mentorship during the cohort.

This question is just to highlight that fact and to give you room to express how you think you might be sharing the knowledge you gained during mentorship.

We have a `mentorship-diary` each mentee updates as a ledger to share progress and experience. You can look this tag under issues.

The last cohort we had mentees sharing videos they had with their mentors on youtube. Writing blog posts, and sharing over twitter.

I hope this makes sense. Please feel free to ask more questions if you need to.

**Comment by madguy02** [comment]
Hi @Bamieh ,

Really appreciate the response, Just another question here : Should we mention the approach on how we are going to share our knowledge that we gain from the mentorship program? As the program hasn't started yet, so we can't really share the experiences yet. Just wanted to clarify about it

Thanks

**Comment by Bamieh** [comment]
We discussed this during the mentorship meeting 2 days ago. We will be updating the readme with more details about this. Thanks for the feedback.

We expect you to share how you will approach sharing your knowledge, and if you already have created articles/blogs/videos in the past, you can share those resources as well.
