### ISSUE TITLE
Mentorship selection process criteria

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#152]
One of the mentees provided feedback on slack channel that the selection process was not clear for the 2nd beta round. We are still experimenting with the best process for selection. we are getting important feedback on the process from mentors and mentees and adjusting accordingly.

## Selection criteria:
This is the current general criteria we are following to choose mentees

### Mentors contribute in choosing their mentee based on the following:
- **Level of experience:**
	Mentor's preference in the level of experience of the mentee.
- **Time availability:**
	At least 2-3 hours intersecting available time between the mentor and mentee.
- **Providing Feedback:**
	Mentors go through every applicant that chose their mentorship topic and read their bios and provide feedback to the mentorship team.

### Mentorship team selection criteria:
- **Diversity and Inclusivity:**
	We ensure that the overall cohort is diverse and inclusive of everyone with different backgrounds, skill sets and experience levels.
- **Level of interest Contributing back to the community:**
	Sharing knowledge is the essence of the mentorship program. We are looking for mentees who are willing to share resources about their experience with mentorship and will help anyone in the community and those who did not get the opportunity to get matched this cohort. Resources may vary from videos, blog posts, issues, or even talks and sessions!
- **Interest level in Node.js and the program:**
	We are looking at the following metrics to gague the level of interest and commitment of the mentees: Mentioning of OSS contribution, The community, interest in nodeJS, how they are using nodeJS, and why they are joining the program.
- **Github contributions:**
	We do check github profile in some occasions to get an indication of activity such as previous contributions to OSS.

**Comment by saulonunesdev** [comment]
i think its important to say that the entire process was 100% transparent and can be checked in the notes at https://github.com/nodejs/mentorship/tree/master/meeting

One more thing, this round is 1 on 1. So from all the applicants only 10 were selected by the mentioned criteria. We are loking for a way to improve the mentors number and to improve the number os pairing mentors 1:n mentees
