### ISSUE TITLE
[Mentorship Diary] Ben and Sneha

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#155]
## [Mentorship Diary] Ben and Sneha

(Mentorship Round 2) @bcoe will be mentoring @snehasi about testing in Node.js

**Comment by snehasi** [comment]
# **Kick off Meeting Notes: July 14 2019**

**Introductions**
---
@bcoe and @snehasi had the first meeting over Hangouts on July 14. We introduced ourselves, talked about our projects and expectations from the mentorship.

**Initial project idea discussion**
---
We discussed proper test coverage and the issues faced in creating complete test sets and validators while maintaining the system. We talked about [nodejs code coverage](https://coverage.nodejs.org/) and [c8](https://github.com/bcoe/c8). Ben also discussed V8, a JS engine and sourcemaps. Our project design isn't finalized yet but we hope to create a project which is useful for the nodejs community.

**Communication**
---
We will use weekly video call, GitHub, Slack and e-mail.

**Next steps**
---

- [Building Node.js](https://github.com/nodejs/node/blob/master/BUILDING.md#macos-prerequisites)

- Reading on Sourcemaps and the javascript test coverage.

- A design document for the project.

**Comment by snehasi** [comment]
# **Node.js Mentorship Meeting 2: Project Plan**
 
Project plan as discussed by @bcoe and @snehasi 

Detecting source map in executing script
---
- http://sourcemaps.info/spec.html
- Detect whether or not the code we're about to compile has a sourcemap.

Creating file with source map for testing
---
- Edited [cjs/loader.js ](https://github.com/nodejs/node/blob/68c83f962e002a47f61648c5aa2adb41dbe6a358/lib/internal/modules/cjs/loader.js#L708
)to detect a source map.
- Created a file with a source map using: `npm i nyc -g` (this can create a working source map that’s Base64 encoded, so we don’t have to load it from a file).

Caching Source Map
---
- For common.js we extract the source map while caching.

Rewriting Stack Trace
---
- Using the sourceMap we have stored in the cache, use a library like: https://www.npmjs.com/package/source-map to find the original position. 
- We then update the error message accordingly.

Next Steps  
---
Code for calling JavaScript from C++.
