### ISSUE TITLE
[Mentorship Diary] Ian and Maria

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#158]
## [Mentorship Diary] Ian and Maria

(Mentorship Round 2) @iansu will be mentoring @mpaktiti about tooling in Node.js

**Comment by mpaktiti** [comment]
# Kickoff meeting (9 July 2019)

We met with @iansu over Zoom. We got to know each other a bit, and chatted about tooling in Node.js.

## Scope & Expectations
During the mentorship period we will be working together on some ongoing projects around tooling. We haven't yet decided on exactly what but there are some interesting stuff going on, like incorporating [rimraf](https://www.npmjs.com/package/rimraf) in core. 
Neither of us have extended time off planned so the next 10 weeks should be productive. We will probably both be out for a few days mid-August. 

## Communication
We will use Slack for daily check-ins and questions. Once @mpaktiti starts working on issues we will plan for Zoom syncs/pairings as needed (weekly or biweekly). 

## Next Steps
Identify the first issue that @mpaktiti can start working on!

**Comment by mpaktiti** [comment]
# First Contribution (14 October 2019)

Recently the [rimraf library](https://www.npmjs.com/package/rimraf) was incorporated in core. The core included some basic tests but the original package included more than that, testing multiply nested directories and different file types like symlinks. My contribution was about adding more tests to the core by copying the logic of the original package (see PR https://github.com/nodejs/node/pull/29815).

## Next Steps
Identify more areas for @mpaktiti to contribute.
