### ISSUE TITLE
Call For Mentors: We'd Love to Have you Help us Level-up Mentees

### ISSUE THREAD

**Issue by bnb** [nodejs/mentorship#16]
The mentorship program is ramping up and we're at an inflection point where we're looking to start getting mentors funneled into the program and ramped up to help others start learning Node.js and contributing to the project 🎉

If you've got experience with Node.js and are interested in helping out and becoming a Node.js Mentor, it would be absolutely stellar if you could [fill out this form](https://docs.google.com/forms/d/1bVcFaCV86tIAJ-8BzdAIAmza-_oozWPchbyii03AS6M/viewform) to note your interest. 

If you're curious about what the expectations and mentality of Mentors will be, be sure to check out this document's [README.md](https://github.com/nodejs/mentorship). More specifically, check out the [mentorship expectations](https://github.com/nodejs/mentorship#expectations), guidelines on [what mentors will help out with](https://github.com/nodejs/mentorship#mentors-will-help-out-in-the-following) and [the benefits for mentors](https://github.com/nodejs/mentorship#benefits-for-mentors).

**Comment by bnb** [comment]
cc @ZibbyKeaton would be stellar if we could get this shared on socials :)

**Comment by ZibbyKeaton** [comment]
@bnb retweeted Myle's post and will queue up some for the next few weeks.

**Comment by oscarrodar** [comment]
Where do I sign as a mentee?

**Comment by ralphtheninja** [comment]
> cc @ZibbyKeaton would be stellar if we could get this shared on socials :)

Shared on Mastodon!

**Comment by Bamieh** [comment]
@oscarrodar read the main readme file of this repo, it has all the details.

**Comment by 4sskick** [comment]
is the program mentorship still opened? I interest to sign as mentee

**Comment by Bamieh** [comment]
@4sskick yess! The program has not started fully yet, please apply by following the links in the main readme of this repo. happy to see you!
