### ISSUE TITLE
Mentorship Program Administration Tool

### ISSUE THREAD

**Issue by detrohutt** [nodejs/mentorship#170]
As I mentioned in the most recent team meeting, I'm considering creating a site/app to house all of the various functionality we find ourselves needing in order to facilitate the cohorts. Right now I'm trying to come up with an outline for a minimum viable product.

My first thought is to move the mentor and mentee application forms into the program so that we'll have complete control over the forms and the results. That will give us a list of all users who applied and from there we'll have a way to move certain users into categories like "mentor applicant"/"mentee applicant" (where they'll start after filling out the form), "mentor", "mentee", "former mentor", "former mentee", etc. This should make sending emails to desired groups of people much simpler. It will also simplify enforcing the 30 applicants per mentor rule.

That's probably enough to start with, but after that set of features is complete I could experiment with creating a way in the app to design quizzes/tests for the different scopes if we decide to go that route. Another potential feature would be handling the timezone/scheduling matching in a more streamlined way.

I'd love to hear what other ideas you all have for what we could do with this.

**Comment by saulonunesdev** [comment]
Amazing @detrohutt 

suggestions compiled from previous mentorship meetings:

- Mentees should apply on Mentors Timezone Availability
- Inform date when the results of pair up will come out so mentees will know when matched and when reply
- Enable an option to collect feedback from mentees and mentors
- Mentees Nationality
- Allow mentee to Share any aditional profile link
- Enable Mentors to choose top 3 mentees ordered
- Check the availability to enable other languages between mentors and mentees 
- Ask mentees that are interested in became mentors

**Comment by Tera99** [comment]
Hello, 
This sounds like a great idea. I would be interested in helping if you need a hand. I have basic JavaScript, Node.js, and RESTful API experience, and I am learning React for the front end. Always interested in learning new things too! Let me know if I can be helpful.

**Comment by lazycipher** [comment]
Hello Devs,
I'm also interested in contributing to this tool. I've got some experience with MERN Stack. I've worked with things like React, Redux, ContextAPI, Hooks, etc and Express, JWT, etc on the backend.
Please let me know if I can be a part of this.

**Comment by saulonunesdev** [comment]
thanks @Tera99 and @lazycipher our next meeting is schedule to Friday Jan/10, please join channel **mentorship** on slack https://www.nodeslackers.com/

**Comment by ngfizzy** [comment]
Hello here. I would like to contribute to this project.

**Comment by Tera99** [comment]
> thanks @Tera99 and @lazycipher our next meeting is schedule to Friday Jan/10, please join channel **mentorship** on slack https://www.nodeslackers.com/

Hello, I am on the slack channel. Thank you!
Where is the info on how to attend the meeting, time, and future meetings posted? Thanks!

**Comment by saulonunesdev** [comment]
Hi @Tera99 i will post an issue next monday to track the meeting and the agenda

**Comment by davidguttman** [comment]
We've decided that we're going to hold off adding more tooling for now, but it might make sense once the program is more established.
