### ISSUE TITLE
Minimum Requirements For Mentees to be in the program

### ISSUE THREAD

**Issue by evahowe** [nodejs/mentorship#172]
Next action item from the last mentorship meeting.  :)  

We had a discussion of what exactly mentees needed to have before they were admitted to the mentorship program.  I am just going to summarize my notes below and would love any input as we try to get the next cohort going.  

- There was a concern that the mentees didn't have a basic knowledge of how to do a pull request or do simple tasks and that the mentors were spending valuable time teaching them these things instead of what their specialties are. 
- Some thoughts on making sure the mentees had basic skills were:
1) perhaps list a PR that they have submitted to a repo to prove they can do it.  There was some concern here that Node is a hard one to submit your first PR to so perhaps another open source project could work too.
2) A Questionaire - Perhaps we could develop a questionaire to ask the applicants where there skill level is.  The downfall to this is that we are relying on the applicants to be accurate and perhaps we don't want to set a high bar to entry.  

Love your thoughts and input!

**Comment by Tera99** [comment]
I came here to ask what the Mentorship committee was looking for in mentee applicants for future cohorts. Once you have settled on exactly what you are looking for, it would be helpful for potential mentees if the README.md of the Mentorship team listed some basic qualifications or skills that it is looking for in new mentees. Taking things a tiny bit further, it would be amazing if there were some kind of resources to help get people up to speed on the basics so they could make the most of their time in the program. Just my 2 cents. I really appreciate everything everyone here is doing!

**Comment by Trott** [comment]
> some kind of resources to help get people up to speed on the basics

For the very basics of getting an initial commit into Node.js, there's https://www.nodetodo.org/getting-started/. Hope that's helpful to some folks.

**Comment by davidguttman** [comment]
Thanks @Trott that's exactly what we needed!
