### ISSUE TITLE
Third cohort

### ISSUE THREAD

**Issue by uzairkorai** [nodejs/mentorship#174]
When is Third cohort is coming up? 
What to learn and prepare before hand to get into it?

**Comment by VSVS** [comment]
+1

**Comment by TygeJ** [comment]
Can you unsubscribe me ? Thanks

**Comment by sojelee** [comment]
Hi team, can I get subscription

**Comment by saulonunesdev** [comment]
Hello, we are running 2nd cohort, we are still planning the 3rd cohort.

You can follow updates on the slack channel #mentorship
https://www.nodeslackers.com/

@tsj7 @sojelee you can turn on/off the notifications by adjusting the watching configuration on the repository
