### ISSUE TITLE
Enrolling requires a Google account

### ISSUE THREAD

**Issue by nukeop** [nodejs/mentorship#18]
Hi, I tried filling out your form but Google informed me that I need to log in to continue. Is it possible to move this to a different provider?

**Comment by Bamieh** [comment]
@nukeop currently this behavior is taken to autofill the email addresses of the corespondents, we can opt out from this feature

**Comment by Bamieh** [comment]
@nukeop Fixed. The forms should no longer be asking for a login.

Cheers!
