### ISSUE TITLE
when will be the next cohort of 2020

### ISSUE THREAD

**Issue by slim-hmidi** [nodejs/mentorship#185]
Hi, 
I want to ask when will be the next cohort of 2020 and how the mentees will be chosen?

**Comment by saulonunesdev** [comment]
Hello @slim-hmidi  at this moment the mentorship initiative is evaluating previous cohorts and improving the process to asserting pairings.

As soon as we finalize this process we will update the README and notify everyone about the next cohort

please fell free to join our slack channel *mentorship* on http://www.nodeslackers.com/
