### ISSUE TITLE
Sync Meetings with Youtube

### ISSUE THREAD

**Issue by saulonunesdev** [nodejs/mentorship#189]
We need to sync Mentorship Zoom Meeting with Node.js Youtube

@nodejs/community-committee

**Comment by saulonunesdev** [comment]
Account To Sync: @davidguttman david@js.la

**Comment by bnb** [comment]
What does that mean @saulonunesdev?

**Comment by saulonunesdev** [comment]
We need to add permissions to the champion account, in order to record and do live transmissions of the mentorship initiative

**Comment by detrohutt** [comment]
Please follow up on this at next CommComm meeting

**Comment by bnb** [comment]
Should be taken care of. Please follow up with me if there's anything else needed here 👍
