### ISSUE TITLE
Conflict for Friday meeting

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/mentorship#19]
Hey All,

Seems like the meeting is currently schedule for 16:00 UTC, which I have a conflict I can't get out of.

I'm available any time before 16:00 UTC or any time after 18:00 UTC if we can change the time.

**Comment by Bamieh** [comment]
Hello @MylesBorins I have no problem pushing it back to 15:00 UTC, does that work for you? what about you guys @bnb @dshaw @hollomancer

**Comment by MylesBorins** [comment]
sgtm
