### ISSUE TITLE
Update Node.js Callendar

### ISSUE THREAD

**Issue by saulonunesdev** [nodejs/mentorship#191]
Update Node.js Callendar with Mentorship Meetings.

@nodejs/community-committee

**Comment by saulonunesdev** [comment]
**Event**: Every Friday 09am to 10am LA Time;
**Attendees**: david@js.la , detrohutt@gmail.com, saulo@paralink.com.br, demolasobaki@gmail.com
**Join url**: https://davidguttman.github.io/mentorship/meeting

**Comment by bnb** [comment]
FWIW @davidguttman it would be awesome to see a proposal for that meeting linking structure within the project itself :)

**Comment by bnb** [comment]
Done.

**Comment by saulonunesdev** [comment]
Thanks @bnb
