### ISSUE TITLE
Agreement on the current mentorship process

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#2]
Opening the door for comments and agreement over the current program structure and process. Mainly from the @nodejs/community-committee and @nodejs/tsc, but all input is welcomed of-course!

## In Brief

Full details about the current process can be found in the main [README of this repo](https://github.com/nodejs/mentorship#process)

![Proposed Mentorship Program Structure](https://github.com/nodejs/mentorship/raw/master/mentorship_process.png)

**Comment by jasnell** [comment]
Initial review on this is that it is solid enough to start. The process can be refined over time.

**Comment by mcollina** [comment]
<strike>This process assumes a duration time for the mentorship program. What is the duration?</strike>

Can you add the fact that it is a 6-month period in the diagram?

**Comment by Bamieh** [comment]
@mcollina In the process section, the last [main point](https://github.com/nodejs/mentorship#duration-of-the-mentorship-program-for-the-paired-up-mentormentee) addresses the duration of the mentorship program.

What do you think about this?
![image](https://user-images.githubusercontent.com/6191849/34827223-22885312-f6e2-11e7-912d-eb0e20f8c4ef.png)

**Comment by mcollina** [comment]
that’s perfect

**Comment by mhdawson** [comment]
+1

**Comment by bnb** [comment]
+1, looks great.

**Comment by Bamieh** [comment]
Closing this as agreement has been reached and an announcement to the projects will be made soon. Thank you guys!
