### ISSUE TITLE
Create a forum for the program

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#20]
Github interface and google forms might be a little unwelcoming for people who applied, as we only provide applicants with a simple "thank you for applying" note after submitting the application.

Having a forum where people can post messages, introduce themselves to the community and ask/answer each other would be super awesome.

The forum will not be limited to only the people who apply for the mentorship program. With the size we have now, and the potential of thousands of applicants in the upcoming months, I think the forum would have the needed momentum to be a good medium to staying in touch and keep the momentum going.

**Comment by codeekage** [comment]
Are you suggesting building a new product for that purpose or using an existing product like slack?

**Comment by Bamieh** [comment]
@codeekage slack is being used to chat and do meetings between mentors and mentees. A forum can be used for mentors and mentees to post about their experience, address each other, post persistent threads and get comments, followers, etc. Something like what https://nodebb.org/ offers. This is just an idea for debate, I am not sure if it aligns with node.

Slack does offer channels for chat, but the free model is not persistent and not truly open for everyone to see (you need to create an account and get an invitation to see the slack channels, private chats are the only way for the pair to talk) , and our main use for it is to have the the mentor/mentee pair meetings and chat, rather than what a forum might offer. IMO it does not harm to have both to give us the benefits of both worlds.

**Comment by softwarecoder** [comment]
if you have seen http://university.mongodb.com/ they provide very good interface which includes, learning path, Forum, Course Progress, Register/unregister etc. We can make something similar, I saw this interface at other website too means it is open source, we can customize and use it.
