### ISSUE TITLE
Glossary links in onboarding document

### ISSUE THREAD

**Issue by choilmto** [nodejs/mentorship#200]
1. Currently, honkit treats lower-case versions of glossary terms as it would regularly. Only capitalized words should be treated as entries in the glossary. Find a way to remove the tooltip and link from words that aren't meant as glossary items. For example, in the definition of MT Channel, the name "node-mentorship-team" does not need to be linked to the definition of Team.

2. Some words containing a term from the glossary are not treated as it should be due to the inclusion of extra letters. For example, under the definition of Process, "Mentees" and "Teams" are not linked and have no tooltips after being pluralized.

**Comment by detrohutt** [comment]
We investigated this and there is no simple way to solve this. It'd involve something like requesting or authoring a change to honkit. While ideally there would be no "false positives", it is not detrimental or confusing enough to justify that kind of effort. Thanks for the report!
