### ISSUE TITLE
Community Committee Agenda Item for March 4th, 2021

### ISSUE THREAD

**Issue by choilmto** [nodejs/mentorship#218]
The Mentorship Initiative wants to help a group or initiative within Node.js find a mentee to onboard. Once the mentee has been onboarded, they will be working with that group or initiative going forward. If interested, our [onboarding documentation](https://nodejs.github.io/mentorship/onboarding/) gives an overview of the process.

**Comment by davidguttman** [comment]
Discussed during https://github.com/nodejs/community-committee/issues/669 and we'll work with @joesepi & @bnb on this 🎉
