### ISSUE TITLE
Helping CommComm manage the community-committee repository

### ISSUE THREAD

**Issue by choilmto** [nodejs/mentorship#219]
The Mentorship Initiative can find a mentee, who will help with some of the [important activities](https://github.com/nodejs/community-committee/issues/639) that go into supporting CommComm. In particular, the mentee can be onboarded to review PRs, respond to issues, and update core documents. The mentee will attend the bi-weekly CommComm meetings and work with regular contributors to complete basic, necessary work on the repository.

**Comment by davidguttman** [comment]
Discussed during nodejs/community-committee#669 and we'll work with @joesepi & @bnb on this 🎉
