### ISSUE TITLE
Inviting mentors to slack channel

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#23]
We are using [nodeslackers](http://nodeslackers.com/) Slack to chat with each other and have the first meeting between each mentor and mentee pair. As an initial step, mentors need to join nodeslackers and join the `#mentorship` channel.

**Comment by csantanapr** [comment]
I requested an invite to [nodeslacker](http://nodeslackers.com/)

I was not aware there was a Slack team for nodejs, didn't see it here https://nodejs.org/en/get-involved/

**Comment by Bamieh** [comment]
@csantanapr nodeslackers is not an official nodeJS workspace, it is used heavily by the community so we decided to go with that. Nodeslackers has 5k+ users, this is beneficial to mentees and mentors alike.

**Comment by csantanapr** [comment]
That’s great yeah I was not looking for anything official is just I was not aware of the existence. 

That’s even better that is a community initiative and so large. 

Looking forward to be accepted

**Comment by Bamieh** [comment]
@csantanapr you should be getting an instant email with the links to join. If not, you already have an account setup in the past, just try to login (this also happened to me)

**Comment by oleg-koval** [comment]
Tried to register with new Gmail account, but haven't received slack invite there. Are there any ways around get the link :)

**Comment by BGiggle** [comment]
I am having the same issue

**Comment by Bamieh** [comment]
hello guys,
For those who are not able to sign up with the form
Try openning slack and logging in. nodeslackers' account name is `node-js.slack.com`

CC @oleg-koval @BGiggle

**Comment by Bamieh** [comment]
# Sign in Quick Guide
For those who signed up and did not get an email, please try the following:

## Step 1: Click sign in to a new workspace

![image](https://user-images.githubusercontent.com/6191849/38455916-0dc83fe4-3a87-11e8-9b37-a97c27d2c5d2.png)

## Step 2: Login to nodeslackers
![image](https://user-images.githubusercontent.com/6191849/38455929-2dfa426c-3a87-11e8-8b85-7e8828a9a175.png)

## Step 3: Fill in email address
![image](https://user-images.githubusercontent.com/6191849/38455934-4a436200-3a87-11e8-9a9f-ca7518efe7d7.png)

## Step 4: Press "Email me a link"

![image](https://user-images.githubusercontent.com/6191849/38455936-547fed92-3a87-11e8-8c50-80c08e36fdaa.png)


## Step 5: Go to email and click sign in to slack

![image](https://user-images.githubusercontent.com/6191849/38455948-747b0afa-3a87-11e8-901f-2bd2199eff79.png)

**Comment by manekinekko** [comment]
Got in. Thanks :)

**Comment by nalejandroveron** [comment]
@Bamieh i got this:
![image](https://user-images.githubusercontent.com/3399236/38990565-3139184e-43b1-11e8-9784-19f6f73bb442.png)

The email is the same as the public one on my github profile: `nahuelav96@gmail.com`
EDIT: Had been able to use an other email account, so no worries about this one guys :)

**Comment by softwarecoder** [comment]
I'm getting below error:

> 
Find your workspace to reset your password

You asked us to send you a password reset link for node-js.slack.com. It turns out the email address sendml2avikesh@gmail.​com doesn't have an account for that workspace yet.

If you’re pretty sure you do have an account, you can find your workspace by trying a different email address.

Please let us know if you have any other questions or feedback.

Cheers,
The team at Slack

**Comment by ChuksFestus** [comment]
You requested a magic link for logging in to node-js.slack.com. Unfortunately, this email address isn't currently associated with that workspace.

**Comment by jxm262** [comment]
@ChuksFestus  are you sure you're logging into the correct url?  Try `https://node-js.slack.com/admin/invites` .  if  you're unable to login, or never received your initial invite link, feel free to email me direct and I'll add you real quick - jxm262@gmail.com

**Comment by ChuksFestus** [comment]
@jxm262 sent you a mail

**Comment by ChuksFestus** [comment]
@jxm262 sent you a mail

**Comment by InsaneSkull** [comment]
Why we don't have invitation link anywhere?  http://www.nodeslackers.com/ never sends invitation link.
