### ISSUE TITLE
No response yet about application status for becoming a mentee

### ISSUE THREAD

**Issue by strongSoda** [nodejs/mentorship#24]
Please resolve my status whether my application for this program has been accepted or rejected so that I can plan my future accordingly. Thanks!

**Comment by Bamieh** [comment]
hello @strongSoda 

Currently we are preparing the mentors to get started, the first round of mentorship did not start yet. Hopefully we will start the pairing process very soon (roughly after this Friday), we will send you an email providing you with more information.

Thank you for waiting.

**Comment by dshaw** [comment]
In the interim you're invited to join fellow Mentors and Mentees in the #mentorship channel of the [Node.js Slack](http://nodeslackers.com).
