### ISSUE TITLE
Starting the matching process

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#25]
We have have some applications dating back from 2/21/2018. For someone that is waiting, this time might feel like eternity. Currently we have good basis and momentum to get started with pairing, and sending emails to people who will halted for next rounds.

**Comment by BeniCheni** [comment]
@Bamieh , great thought on this open issue, ✌️ Looking forward to the communication about the matching process.

**Comment by benjcal** [comment]
Thanks for the update! I was literally right now writing a tweet to see what was going on with the applications 😅

**Comment by rkterungwa16** [comment]
I was also worried. I thought something was wrong with my application.

**Comment by Mindaugas-Jacionis** [comment]
Hope for the good news 🤞😄

**Comment by Bamieh** [comment]
I have sent an email to all mentees giving them the current status of things, and asking them to join the slack channel until the first round is started. I attached a copy of the email payload here:


<details><summary>Email To Mentees </summary>
<p>

________
I hope this email finds you well mentee!

First I would like to thank you for taking the time to apply and join Node.js mentorship program. Hopefully we will reach awesome goals together!

At this moment, the first round of mentorship did not start yet as we are preparing the mentors.

Hopefully we will start the pairing process soon. In the interim you're invited to join fellow Mentors and Mentees in the #mentorship channel of the Node.js Slack.

Link to nodeslackers: http://www.nodeslackers.com/
________
</p>
</details>

**Comment by benceHornyak** [comment]
@Bamieh I signed up around 2018 January, but didn't get any email. 
So I just refilled the google form. :smiley:  
 Hope that's not a problem.

**Comment by codeekage** [comment]
Are you on the slack? nodeslackers.com

**Comment by codeekage** [comment]
Please do that to stay updated with our processes

**Comment by benceHornyak** [comment]
Registered, thanks!

**Comment by Bamieh** [comment]
Beta Matching process will start on June 15
