### ISSUE TITLE
Mentorship Directory

### ISSUE THREAD

**Issue by codeekage** [nodejs/mentorship#26]
Created something with just JS here no backend frameworks, flexing muscles... think we might probably need it for easy pairing? don't know how efficient it might be? https://codeekage.github.io/nodejs-directory/

**Comment by Bamieh** [comment]
It would be cool to have such tool. Given the huge amount of members, a simple list would not be super practical. I think this could be steered back to the forum idea as well. I do not see how this could help in the pairing, can you share your thoughts?

**Comment by dshaw** [comment]
I think we are going to want a publicly available list that we publish to this repo. Let's build up the basics here and then we can build resources to make things a bit more efficient in subsequent iterations.
