### ISSUE TITLE
No response  about application status for becoming a mentee.

### ISSUE THREAD

**Issue by slim-hmidi** [nodejs/mentorship#27]
I haven't received yet an answer about a mentee application. Please answer me about my application.

**Comment by dshaw** [comment]
Hello, @slim-hmidi.

Thank you for requesting to join the Node.js Mentorship program of the Node.js project. As you likely already know, Node.js collaborators are all volunteers. We are at the beginning stages of this program. We are currently working with our first group of Mentors to get them setup. Once that work is complete, we will begin onboarding Mentees.

In the interim you're invited to join fellow Mentors and Mentees in the #mentorship channel of the [Node.js Slack](http://nodeslackers.com).
