### ISSUE TITLE
Area of Interest for Mentees 

### ISSUE THREAD

**Issue by codeekage** [nodejs/mentorship#29]
All mentees should comment in the discussion their area of interest for the Node.js Mentorship Programme.

**Comment by u5r0** [comment]
Area of interest, like a [Working Group](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md)?

**Comment by Bamieh** [comment]
@codeekage I believe we should be creating a list of possible general areas of interest around the nodeJS ecosystem, and adding it to the submission form.

**Comment by codeekage** [comment]
I think the form is almost too late... we can just have them do it here. Probably get them to watch the next meeting, while we explain the node.js ecosystem and all the it's projects, working groups and know those that just want to learn Node.js.

For now, this issue can be closed, till after the next meeting. any +1 on this?

**Comment by Bamieh** [comment]
@codeekage the mentorship program is a continuous program, so it is definitely not too late to update the form, for those who have already applied (600+ mentees), we will have to fill these retroactively. i cannot imagine having 600+ comments on this issue, it will be overwhelming and very hard to keep track of.

**Comment by u5r0** [comment]
Two forms then, one for those who have already applied, and updating the other one for the newcomers ;)

**Comment by Bamieh** [comment]
@usrnull sounds plausible to me! We should be starting with this to create a suggestions list for mentees and base the areas of interests around them ( https://github.com/nodejs/mentorship/issues/30 )
