### ISSUE TITLE
pair programming

### ISSUE THREAD

**Issue by mcollina** [nodejs/mentorship#3]
Remote pair programming is often hard, and it requires specific tools. It's also an activity that can take up significant time. Committing to 1-2 hours every month is feasible, while committing to an afternoon of pair programming is something completely different. This does not include any timezone problems.

I would note that it is optional, and it depends on what the mentor and the mentee could do.

**Comment by Bamieh** [comment]
@mcollina Definitely I agree. it should be optional based on what both parties agree upon and how much time they can dedicate.
