### ISSUE TITLE
We need more active members of the WG

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#32]
As this project is gaining more and more attention, it would be nice to get more contributions from the members of the working groups, in mentoring or joining one of the mentorship subgroups. With your help, the mentorship program will directly benefit the working groups as well.

CC @nodejs/coreworkinggroups @nodejs/community-committee

**Comment by gibfahn** [comment]
I'd be happy to mentor, how does one sign up?

**Comment by AyushG3112** [comment]
@gibfahn The [README](https://github.com/nodejs/mentorship/blob/master/README.md) has the details for applying. And thanks for the intitiave.

**Comment by bnb** [comment]
FWIW I will vouch for @gibfahn as a strong mentor 👍

**Comment by dshaw** [comment]
As I mentioned at our last Mentorship team meeting, we also are explicitly in need of women on the Mentorship team to help ensure that the program is well represented and safe for all participants.

**Comment by dshaw** [comment]
@gibfahn We'd love to have you join as a Mentor and all Mentorship team members will have the opportunity to mentor.

What we need even more than Mentees and Mentors is more Mentorship team members: https://github.com/nodejs/mentorship#nodejs-mentorship-team-members . There are currently only 4 of us helping coordinate over 500 people. I sent you an invite to our team meeting on Friday if you'd like to explore this a bit more. Worst case, we are helping onboard Mentors and you can join the cohort we're working with now.

**Comment by ryanmurakami** [comment]
I would be interested in joining the working group.

**Comment by MylesBorins** [comment]
I can likely volunteer more help on this. When is the next wg meeting?

**Comment by dshaw** [comment]
@mylesborins Friday 9am PT / noon ET

**Comment by gibfahn** [comment]
I'd be interested in helping out with the mentorship team, but I'm not going to be able to make that meeting.

**Comment by detrohutt** [comment]
As I mentioned in #44 I’m happy to help out any way I can. I’m not currently a member of any WGs but if I had to choose one to join it’s this one because I think it is the most well-positioned to positively impact the ecosystem as a whole to the greatest degree.

**Comment by ankibalyan** [comment]
I'm happy to help out in any form, Though, I've been in working with node.js from last 2.5 years only out my 3.5 years of professional exprience.
I'd like to come forward and give something back to community as well. But still, I may need some assitance :sweat_smile: 

Thanks!

**Comment by hemanth** [comment]
I would like to put in my 🐜contributions to this!
