### ISSUE TITLE
Peer support subgroup for mentors

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#33]
We need to create a sub-group to help guide mentors, initiate kick off meetings, and answer any questions the mentors have.

Not all of our mentors have mentorship experience, hence they will need some guidance, resources and a place to ask questions at times where they do not know how to deal with certain situations.

I believe the support group will carry most of its activity on the slack channel as it is our main communication channel for mentorship.

**Comment by truongminh** [comment]
Totally agree with @Bamieh 
And we need some kinds of learning paths, which help both mentors and mentees better understand the direction where they should focus on.

**Comment by Bamieh** [comment]
Closing this since it has been resolved long time ago. We have created a private slack channel for the mentors and the mentorship team to support each other.
