### ISSUE TITLE
How soon the mentees will be matched with their mentors?

### ISSUE THREAD

**Issue by fullstackguyhere** [nodejs/mentorship#34]
I have applied to be a mentee and I have lot of free time with me and hence would like to make contributions on project as soon as possible.

**Comment by dshaw** [comment]
@fullstackguyhere You can begin to make contributions to the Node.js project at any time! Being accepted as a Mentee is indirectly related to contributing to Node.js.

We have a very deep backlog of Mentee and we currently have way more Mentees than Mentor capacity. In the interim you're invited to join fellow Mentors and Mentees in the #mentorship channel of the Node.js Slack.
