### ISSUE TITLE
Mentorship Moderators

### ISSUE THREAD

**Issue by codeekage** [nodejs/mentorship#35]
Moderator: A mentor that must have shown some sort of interest by reaching out to help assist in one way or the other by either sharing ideas to help make what we're doing more Awesome and to give mentees a lovely 6months. 

They'll basically be facilitators of the Node.js Mentorship Programme, a sub-group of the mentorship team.  #33

**Comment by dshaw** [comment]
In our last meeting, we had an action item to reach out @nodejs/moderation to get feedback and build on existing experience. Maybe these Mentor moderators could be affiliated with the Moderation WG.

**Comment by benjamingr** [comment]
I can bring this up in the next moderation team meeting - though I'm not sure I understand the motivation to have a separate moderation team than the org one.

**Comment by codeekage** [comment]
They could? @dshaw  or maybe they will probably stick with facilitating since the Moderation WG deals with a more admin privileged task. Correct me if I'm wrong.

**Comment by benjamingr** [comment]
The moderation WG deals with moderating the GitHub org, repos and related channels. The moderation WG currently holds org-admin status but we don't like it nor do we intend to keep it for long (and certainly not longer than necessary). 

What would you expect a mentor moderator to do?

**Comment by codeekage** [comment]
1. Facilitate onboarding (know what a mentee wants to learn and find the right match of mentor)

_**Later in the future, this can be added to the task**_ 
2. Help checkmate mentors and mentees
3. Feedback on mentors and mentee (like an assessment if a mentee is actually learning or a mentor is actually mentoring, we certainly don't want to have some mentees after 6 months not being happy with the whole process).
4. Check mentors mentorship status, if a mentor has been inactive for some reasons.
5. File complain from a complaint about mentor-mentee relationship (a mentor speaking rudely to a mentee or any of such sort)

These basic ones for now.

**Comment by benjamingr** [comment]
That sounds interesting - I'm not sure 'moderator' is the term I'd use for it and I'm not sure the moderation team can help based on our experience (as a team, not as individuals) with anything other than:

> File complain from a complaint about mentor-mentee relationship (a mentor speaking rudely to a mentee or any of such sort)

Which would basically constitute reaching out to the team via nodejs/moderation or `report@nodejs.org`.

**Comment by codeekage** [comment]
Yea, maybe with your help on the moderation team such complaints can ping you and actions can be taken from there.

**Comment by wswoodruff** [comment]
[edited] Hey ~guys~ friends! I was directed here as someone who is interested in being involved can't dedicate enough time to be a full-on mentor. I think moderators can act as community facilitators -- seems like ideas are going towards helping enforce a code-of-conduct and do some light project management or progress assessment. Would `facilitators` be a better term? Who else wants to be a moderator? And mentors should not also be moderators, it's a conflict of interest

**Comment by bnb** [comment]
@wswoodruff project management is _always_ needed! I don't think many groups would turn away someone looking to help out with that 😅 

As a side note, I'd like to suggest avoiding the usage of `guys` to refer to a group of people - especially in the context of a mentor/mentee and Code of Conduct + Inclusivity discussion. It can (regardless of intention!) make individuals feel excluded.

**Comment by wswoodruff** [comment]
@bnb You're right about referring to a group with a gender-infused word -- I edited my comment above to reflect

**Comment by codeekage** [comment]
Closing this issue.
