### ISSUE TITLE
1-many proposed mentorship structure

### ISSUE THREAD

**Issue by bcoe** [nodejs/mentorship#43]
there are two potential approaches to mentorship that have been proposed
going forward:

* 1-many, which would entail one mentor helping a group of mentees.
* 1-1, which would pair off mentors and mentees in a one on one relationship.

this issue outlines what I'm picturing the 1-many relationship would look like:

## Project Based

we would center the 1-many mentorship around GitHub projects:

* these projects would run using an open-source workflow on GitHub; 
  conversations centering around GitHub issues and pull-requests.
  * this provides a written record of the mentorship process, fitting with
    feedback given by the moderation team.
* the projects would be chosen to reflect the goals of the mentees and to
  benefit Node.js, e.g., _"make Node's test coverage use the new inspector API"_,
  _"speed up node's test suite"_, _"speed up Node.js startup using V8 snapshots"_,
  etc.

## Individual Mentorship Provided as Needed

As mentees work on the project they've been paired with, there will certainly be
times that individuals:

* need help getting started on a ticket.
* have questions about feedback given on a pull-request.
* want to share a particularly funny animated gif with the mentor, etc.

Mentors would still be able to provide 1 on 1 mentorship through slack in these
situations.

## Pros

* mentorship centers around a project, providing a clear goal for the mentorship
  program.
* there are 10 times as many mentees as mentors, a 1-many relationship would
  allow more mentees to be supported by the program.
* running the program like a GitHub project helps teach open-source practices
  to mentees.

## Cons

* a less personalized experience for each mentee.
* mentors need to be comfortable wearing a project-managment hat, along with
  providing technical feedback.

**Comment by detrohutt** [comment]
Hopefully my input is welcome here. If this is just for members, please let me know.

I definitely see the merits to this approach, especially with the disproportionate amount of mentees to mentors. My main concern is this will put too much of an extra load on mentors and you may end up with even less mentors when some decide they can't accept the increased demands on their schedule.

I'm assuming the required 1 hour meeting per month would take place with the group all together vs 1-on-1's. But even so...

From the README:
> In addition to the meetings, the mentor should champion any PR submitted by the mentee during the mentership[sic] program in the Node.js project.

So, with 10 mentees, the time commitment would increase potentially ~10x, unless I'm missing something. If I am, please clarify.

I watched the meeting today on youtube and have an idea for a potential solution I'll explain in an issue which I'll make shortly.

**Comment by franher** [comment]
Hello, 

this approach could lead to some mentees with higher skills or background to become "mentors"   whose will help the real mentor to manage and support the other mentees of the group. 

This could balance the numbers of mentors vs mentees.

**Comment by erinishimoticha** [comment]
Con: Mentees would need to commit time to taking on a new project that is possibly irrelevant to them and would not be able to focus their mentorship around their current projects.
