### ISSUE TITLE
1-1 proposed mentorship structure

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [nodejs/mentorship#46]
For the mentorship program, we have two structures for mentor/mentee mapping that have been proposed:

- 1-many, which is like a mentor being matched with a number of mentees 
- 1-1, which maps one mentor to a mentee

You can find details on the 1-many structure here: #43 

## Implementation
The matching process (not the mentorship itself) would be done on Github. When there's a mentor-mentee pair, there is an announcement on Github (can be by opening an issue) so there's a public record. This can then be used as a feedback channel and also gives us an idea of mentor/mentee involvement.

## Pros
- This approach is more mentee-focused, and this way, it is easier to track mentee involvement and progress. In case of unavailability, mentors/mentees can be re-assigned.
- Mentees have a more personalized experience.
- It is easier for mentors to maintain commitment level regardless of sudden changes in their own schedule, since there's only one person to manage.
- Seeing that we are still testing, it is easier to transition to 1-many if we discover that this approach doesn't work out too well. It would be much tougher to transition from 1-many to 1-1 without facing a number of issues like the feeling of losing momentum, and the "emotional" dissatisfaction of shutting down groups especially on the mentees side.

## Cons

- There are currently many times more mentors than mentees, so 1-1 relationship doesn't give us speed in implementing the mentorship program.

**Comment by Bamieh** [comment]
@OpesanyaAdebayo you brought very important points to the discussion mainly this
> It is easier for mentors to maintain commitment level regardless of sudden changes in their own schedule, since there's only one person to manage.

and this

> Seeing that we are still testing, it is easier to transition to 1-many if we discover that this approach doesn't work out too well. It would be much tougher to transition from 1-many to 1-1 without facing a number of issues like the feeling of losing momentum, and the "emotional" dissatisfaction of shutting down groups especially on the mentees side.


Personally I am in favor of doing 1-1, or a well designed hybrid of both. While I certainly would love to have the mentorship include everyone as soon as possible, I do prioritize the quality gained from the program rather than the numbers.

**Comment by detrohutt** [comment]
I agree this is very well done and these are very important points indeed.

@Bamieh regarding this:

> I do prioritize the quality gained from the program rather than the numbers.

I'd like to point out that the two are somewhat related. Even with careful ordering/prioritization of who gets mentored first, the more people left out for a long period of time, the more high-quality mentees you risk losing.

**Comment by AnthonyLenglet** [comment]
If it is possible for us to gather enough mentors in order to achieve this I'd be all for this structure 😄

**Comment by Bamieh** [comment]
@AnthonyLenglet Usually new comers and beginners are more than the experts in any field, so I think we should be filtering mentees to keep the numbers close to each other

**Comment by OpesanyaAdebayo** [comment]
@Bamieh Thanks for your response.

> I think we should be filtering mentees to keep the numbers close to each other

It would be nice to see some detail on what you have in mind. 😄

**Comment by ankibalyan** [comment]
I think we can go with some hybrid approch with #43 and #46 Something like below

1. we can dived the mentees in group of 2-3 on a single project.
2. 2-3 group per mentor, so ultimately 4-8 mentees under one mentor.
3. It may also depend on the mentees as well, that they want to go with team bases or not.
4. Team/ group can help people how exctly contribute on open source project, working along side, feature bases etc.
5. Team can be done in couple of ways (based on any other expience or skill they want to develop or roles etc)
6. Working 2-3 people on the same project can help them stay motivated with progress of project.
7. A little better for mentors as well to focus on lesser project than in 1-1 relation.

Cons:
1. Could be challenging to form groups and assigning roles in project.

There could be other cons which you may point with this approch.

Thanks

**Comment by ankibalyan** [comment]
The idea is to learn remote, collaboration, open source, better projects.

**Comment by nosark** [comment]
I like @ankibalyan s idea. With there being more mentors than mentees, A team based approach with a few mentors per team would provide for an ideal learning experience while simulating real development. Should life get in the way, and a mentor not be able to be as active for some time period. Each individual would have their teammates to fall back on.  Plus everyone would have teammates to help keep each other accountable. I don't know what the ideal number of mentors/mentee ratio should be. But a hybrid approach of #43  and #46 would be a good idea in my opinion.  If I had to choose between the "1-1" and "1-many" I would chose "1-1" because I feel like the quality would be better than  a "1-many" situation. I believe that the "1-many" may get a little hectic for the mentors and could cause a loss in quality of information. 

Either way I am excited to get this program going!

Cheers!

**Comment by samie820** [comment]
Although I am in support of 1-1, someone on the slack channel pointed to an issue of commitment. If we were to go with 1-1, and a mentee eventually looses motivation to see the program through, that might be a case of wasted effort. So,  I think the hybrid approach might just work in helping us filter out the serious mentees.

**Comment by sushantmagoo** [comment]
Even I also think that 1 to 1 will provide a better experience and learning to mentees and also will be helpful to nodejs foundation reach the end goal of mentorship program but I am also curious about (to what  @Bamieh  above writes) the process and criteria of selection of mentees.

**Comment by OpesanyaAdebayo** [comment]
@samie820  Good point, but I don’t think 1-many solves the problem of mentees quitting. It only makes it less obvious when a mentee quits. 1-1 makes it more obvious, hence making it easier for a waiting mentee to be assigned a mentor.

And personally, I haven't really seen a practical hybrid approach. It usually ends up being 1-many.

**Comment by ankibalyan** [comment]
@OpesanyaAdebayo I think, loosing motivation can be reduced with small team based approch, It feels a lot more than just mentorship beside projects they choose isn't much happening one.
Team cheers when somethings is accomplished, it shows more success, build good relations, many more benifits. 
Also It will be easier for mentors as well, they just have to look on 1-2 project only.. which is what ~1-1

**Comment by erinishimoticha** [comment]
1. Can we jumpstart the evaluation of these options by researching what other mentoring programs have done?

1. If we have many times more mentors than mentees, do we really need speedy onboarding of mentors?

1. Would a 1:1 structure lead to orphaned mentors and mentees when people give up or become unresponsive?
