### ISSUE TITLE
Identify Mentees Who Could Help Out As "Teaching Assistant"?

### ISSUE THREAD

**Issue by BeniCheni** [nodejs/mentorship#49]
#### Mentorship Program Add-On Support For Mentees?
Identify some mentees who are familiar with the node CoC, build process, PR process => CI + Landing (and even have contributed from docs to unit test, or even cooler / real features) , and create a group perhaps called "**_Mentorship Teaching Assistant_**" or a similar tomorrow terminology

#### Benefits:
This group of "_teaching assistants_" can be the 1st level support of other mentees that have questions about code of conduct, build / PR process (or what have you) kind of questions that some "_more experienced_" mentors in the teaching assistant group can join in to help.

The mentors then can focus on the process of 1-n or 1-1, with now some level of understanding who mentees had been helping out and perhaps the expected experiences of tech or open source etiquette are there to work with. So mentor can really teach / grow the "_progressive_" mentees, whom really want to collaborate with the mentorship program to get "_deeper_" in Node.js and learn how to contribute back to Node.js that we all love about, in which it also will make the common goal of *Mentorship* a successful win-win situation!

For some of the mentees who are interested to become mentors in the future phrase of the mentorship program can also practice communication & coaching style, to learn how to be *_objective_* and *_helpful_*. I feel like hypothetically speaking, going through and being "_helpful_" in an " _imaginative_ **Teaching Assistant**" would be like graduation to becoming the next "_mentor_". 

#### Potential Issue?
One problem I can anticipate in my proposed _**Mentorship Teaching Assistant**_ approach is that it may create a sense of imbalance among mentees. There shouldn't any unfriendly "competition" if there's. The program should foster collaboration, IMO.

I'm happy to hear your thoughts, or close this issue if the topic is not worth of being discussed. You are definitely welcome to share your thoughts. 🙏 in advance. ✌️

**Comment by appelgriebsch** [comment]
Ideally this could result in a structure in which the already advanced node.js users can take care about the beginners, and the node.js team members can focus on spreading their (internal) know-how to the advanced users first. So to say: train the trainers… The team can ask existing node.js users from the mentee group if they are willing to help out with training the beginners. Nevertheless a kind of curriculum has to be in place so the volunteers have a guideline for mentoring beginners and the node.js team have the confidence that the training is going in the right direction.

**Comment by nickParis11** [comment]
I have way more experience as a teacher ( i taught for several years at various colleges and university in France ) and as a learner ( i try to take part to one big learning program every year ) than in node ( i am a future "really average" mentee ). 

Therefore, please take what follows as an input on how successful educational program are usually built more than anything else.

1. I think TA are a great idea, 
2. I think TA may not be sufficient to maximize both teaching and learning

Usually Mentors have very little time, so they need three types of people around them : 
a- TA
b- Education assistant ( help coordinate the teachings / take feedback from mentees / help mentors to incorporate feedback / act as a level 1 support on questions about the learning path [ not any tech support of course, that would be TA's job ] ).
c- Administrative assistant ( collect registrations - help coordinate plannings - and millions of other stuff ).

As i do not feel i have the level to act as a TA, i d be happy to act either as an Education assistant or Administrative assistant to help this program thrive and give back to this exciting program and community.

**Comment by BeniCheni** [comment]
> a- TA
> b- Education assistant ( help coordinate the teachings / take feedback from mentees / help mentors to incorporate feedback / act as a level 1 support on questions about the learning path [ not any tech support of course, that would be TA's job ] ).
> c- Administrative assistant ( collect registrations - help coordinate plannings - and millions of other stuff ).

Thanks for sharing the idea of _Education Assistant_ and _Administrative Assistant_ roles. They all sound very cool roles to support the success of the mentorship program, definitely worth of hearing feedback from other mentees / mentors / mentorship team members.

My personal sentiment is that if there were to be any "_helpful_" process around mentees' participating/contributing back to the program, that's being ideated to implement, the process could start with a "_lightweight_" version. Perhaps having much granularity of these defined roles for mentees to help out may be too "_rigorous_" to kick off & execute the program quickly, and have the lesson learned from the process of the program for the next round in near future. But let's ~lear~ hear more thoughts in the thread of this issue. ✌️

**Comment by ankibalyan** [comment]
This idea is really good, but I'm not sure how how filtering of such member will gonna happen, It could be a little challenging.
Another challlenge What I can see is Quality, Not sure If this can also be tracked if 1-1 mentorship goes with newly trained Mentors. 

Just a thought.

**Comment by BeniCheni** [comment]
👋, thanks for previous comments regarding this issue to explore the idea. I’ve also watched the last mentorship team meeting on YouTube and paid close attention when this topic was brought up for discussion. And I’m glad some of the potential concerns of this idea have been clarified that, the intent of this idea is for mentees who wish to contribute back to the mentorship program to help other mentees, and for the mentees who aspire to become mentors someday can learn and grow by helping back.

The issue has been open for 20 days. I’d like to keep the issue list “_clean_” if closing this open issue created by me, if you guys feel that this issue does not need further discussion. Please advise and I am more than happy to update accordingly. 🙏🏻 and will look out for your further advice from the mentorship team memebers and mentors.

**Comment by thatshailesh** [comment]
Hi Guys,

I have submitted the mentee form 2 weeks ago and mentioned start date as 1 June, any idea what would be the next step? or I should wait?

**Comment by BeniCheni** [comment]
@thatshailesh, thanks for checking in. I’d recommend to register the active Node.js Slack channel titled “_#mentorship_” via [HERE](http://www.nodeslackers.com). Once you registered & able to sign in the Slack chat, please review the details in #mentorship channel, and get the latest updates about the Node.js mentorship program.

**Comment by thatshailesh** [comment]
@BeniCheni  Sure, I am already registered in slack channel but can't see `mentorship` channel 
There are only 3 `intro` `announcements` and `general`

**Comment by detrohutt** [comment]
Hi @thatshailesh I'm not sure what version of slack you're using, but in the OS X version, if you click the "Channels" heading above the channels you mentioned, it'll let you browse all channels and you can search for "mentorship". :)

**Comment by BeniCheni** [comment]
Hi @thatshailesh, glad to hear you could sign in Slack chat already. The `#mentorship` channel seems to be a public channel, so you should be able to search and find the `#mentorship` channel and find the details you need. 🔍 😎 (Hope you could find what you need. Have a good day!)

**Comment by thatshailesh** [comment]
Thanks, I found it, see you guys there 👍

**Comment by Bamieh** [comment]
Hello @BeniCheni the TA is a very good idea, and I love your wording on this issue. We actually had this discussed earlier. Currently we have a private slack channel for TA.

The channel is shared between the mentorship team and the mentors, in which we help each other as needed. At this moment we do not have special people delegated for the TA role, since our mentors and the mentorship team have the needed experience. Do you think this is enough for now?

**Comment by Bamieh** [comment]
@nickParis11 the 3 tier support (if i may call it that) sound super exciting, thank you for sharing your knowledge. Currently we are starting small to make sure our model makes sense and is optimized towards learning and having a pleasant experience for everyone. Do you mind joining the next meeting so we can discuss this? I believe an education assistant with your experience would be awesome even if we are starting small.

**Comment by Bamieh** [comment]
Hello @BeniCheni the TA is a very good idea, and I love your wording on this issue. I  believe we actually had this discussed earlier, the resolution was to create a peer support group for mentors (https://github.com/nodejs/mentorship/issues/33).

Currently we have a private slack channel shared between the mentorship team and the mentors, in which we help each other as needed, then the mentor reflects his resolution back to the mentee. At this moment we do not have a team delegated for this role, since our mentors and the mentorship team have the needed experience to help each other as needed. Do you think this is enough for now?

Having the mentees ask directly any mentor might introduce friction, this is why we followed the above approach instead.

**Comment by BeniCheni** [comment]
Hi @Bamieh, thank you for the feedback on the proposed TA idea, which obviously the mentorship team already covered this "_TA_" thought in #33 😄, which resulted in the private Slack channel between mentorship team and mentors. I agree that the SLA of the private channel would be enough for now. 👍

###### A thought (not urgent to be explored really):
If the peer support group needs to scale out, and I can be anything useful 😅, I'd like to try to contribute back to the peer support group community as well.

Not sure if there's any thought, or discussion, around the topic: _how a "_graduated_" mentee (let's say) can help out to contribute back to the peer support group_?

**Comment by Bamieh** [comment]
@BeniCheni Although this is not discussed thoroughly yet, we do have the intention to encourage mentees to contribute to the mentorship after their graduation (becoming mentors for example). Inviting the graduated mentees to the support group sounds plausible

**Comment by Bamieh** [comment]
thanks to nick for offering help on this issue, i will close this since it is being followed up upon in other issues.
