### ISSUE TITLE
Mentors: Please create a mentor bio

### ISSUE THREAD

**Issue by detrohutt** [nodejs/mentorship#55]
The Mentorship team is planning to have a one-month trial run starting on June 15th to see what works and what doesn't before we roll out the full program. We'd like to try some mentors in a 1-to-1 relationship with their mentee, and other mentors that take on several mentees at once.

Any mentors are welcome to participate, on the condition that you agree to provide feedback to the Mentorship team on your experience along the way to help us determine what the pros and cons of each approach are.

If you would like to participate please open an issue on this repo titled `[Mentor Bio] <your name>`. This issue will be used to help mentees find a mentor they feel is a good match for them. Give some basic information about yourself like whether you'd like to be a 1:1 or 1:many (but be specific, like 1:2 or 1:3) mentor,  what scope/area(s) of Node.js you'd like to mentor on (a specific repo, working Group, or initiative), and your background and experience. You can include whatever else you think your potential mentee(s) would find useful.

### Example Bio

Here's one way a bio issue could be structured. Feel free to use this as a template, but it's not necessary if you'd like to format yours differently.

> Issue title: [Mentor Bio] A.J. Roberts

```markdown
## A.J. Roberts

Basic info | &nbsp;
-|-
Preferred mentoring format | 1:3
Mentoring scope | Node.js c++ core
Background | Hobbyist Web App Developer
Experience | 10+ years

### About me

Hi! My name is A.J. and I am here to help. I spent many years as the owner of a small computer
repair shop, where I learned patience and how to explain things in a way where anyone can
understand. So if you're a little intimidated by the idea of working with a mentor, I might be
a good choice. I also have lots of free time, so when you have questions I can get back to you
generally really quickly, so you can stay productive! Comment on this issue if you have any
questions.
```

**Comment by BeniCheni** [comment]
Thanks, @detrohutt et al, for initiating this open issue to exemplify a mentor bio. Would you think a mentee bio would be useful in the same context? If so, here are some questions about mentee bio which I'd like to discuss along in this open issue:

- What do you think about using an open issue for a mentee bio with similar style of content and Markdown formatting?

- Let's assume that open issues can serve as a "_rolodex_" for the profiles of mentors & mentees, how would you envision the process of matching the mentors & mentees from the "_rolodex_" to support 1:1, or 1:many mentorship format?

- Are there any suggested "_good_" practices (i.e. using GitHub issue labels or other issue features) that can help facilitate the "_matching_" process to better match the scope/area(s) of Node.js, which mentor(s) with interests & expertise and which mentee(s) with similar interests & aspirations?

**Comment by ankibalyan** [comment]
We can create milestone checklist for each or mentor, where mentee to be assigned, the project or topic to track the same.

mentee / mentor allow them to send pull request for match.

**Comment by detrohutt** [comment]
Closing for now since we have bios for all this round's mentors. Can reopen as needed.

**Comment by detrohutt** [comment]
@BeniCheni Sorry I forgot to respond to your questions. The main issue with mentee bios is volume. We've got hundreds of mentees and it just wouldn't scale well. We're even planning to move away from this format for mentors after the beta period, I think. As far as how to better match mentees to the correct mentors, that's something we're still trying to figure out. Right now, in my personal opinion, the biggest problem we have is the limited number of scopes we have mentors for. I'm hoping within a few rounds we'll have most of the areas of the Node.js ecosystem represented by at least one mentor each so that mentees can be mentored in exactly what they're interested in, rather than having to choose from what's available. People are going to make better contributions in an area they're genuinely interested in.
