### ISSUE TITLE
[Mentor Bio] Diego ZoracKy

### ISSUE THREAD

**Issue by DiegoZoracKy** [nodejs/mentorship#61]
## Diego ZoracKy

Basic info | &nbsp;
-|-
Preferred mentoring format | 1:2 
Mentoring scope | General, back-end
Background | Software/Web/App Developer (front-end and back-end ) and Manager
Experience | 10+ years

### About me

Hello! My name is Diego, aka ZoracKy. I am here to help people interested in know more about Node.js. JavaScript has been part of my daily life since the beginning of my journey as a programmer, and during the last 5 years I've developed tools, OSS libs and production projects using Node.js, included in the following scopes:  

* API servers (Restify, Express, OpenAPI)
* Desktop Apps (Electron)
* Databases (MongoDB, SQL Server, Excel Spreadsheets)
* Workflow Automation (FS)

I'm the creator of [MagiCLI](https://github.com/DiegoZoracKy/magicli) which is a lib built to help us by giving us a way to create a CLI or to execute any module via command-line effortlessly. Also others published modules focused on Node.js/JS can be found on my GitHub Profile: [github.com/DiegoZoracKy](https://github.com/DiegoZoracKy)

Recently I proposed the creation of [Node.js People Everywhere (npe)](https://github.com/nodejs/community-committee/issues/184). It is a project that I believe it can be very good for our community and would be great to find mentees interested in be involved on it.

You can also find me on [Twitter](http://twitter.com/diegozoracky) or [Medium](https://medium.com/@DiegoZoracKy) where I'm usually talking about software development in general, and most of time focused on Node.js and JS.

**Comment by Bamieh** [comment]
Hello @DiegoZoracKy :wave: do you mind joining the nodeslackers slack channel? details can be found here https://github.com/nodejs/mentorship/issues/23

**Comment by DiegoZoracKy** [comment]
@Bamieh 👍
