### ISSUE TITLE
Follow up discussion for 2018-06-15 meeting

### ISSUE THREAD

**Issue by detrohutt** [nodejs/mentorship#66]
We covered a lot of ground in the meeting and left some things a bit unclear so I thought it'd be helpful to have an explicit list of action items and things that may need further discussion.

### Secure more 1st-round mentors (from Node.js Members)

Each mentor we can onboard potentially broadens our available scopes and accelerates our timeline to reaching program stability. We could double our mentors each round so even a few extra mentors in round 1 could mean lots more within the next few rounds. I'll list a few of my ideas below but would love to hear more ideas.

### Invite 1st-round mentors to Friday's meeting

I think it'd be valuable to have the mentors help brainstorm or just share their views on how things are going from their perspective, what their expectations are, see if they need clarification, make sure we're all on the same page, etc. Thoughts on this?

## Action items

I organized these for easy reference i.e. Item D-4

### A. Claimed items from the meeting

1. ~Draft update letter~ - @detrohutt
1. Gather/provide WG descriptions on Wishlist README - @detrohutt
1. ~PR for meeting notes~ - @Bamieh
1. ~Reach out to nickParis11~ - @Bamieh
1. If nickParis11 is on board, ask "general" mentors if they'd like to TA 1st round - @Bamieh
1. Reach out to Trott and Myles - @dshaw

### B. Potential ~1st-round~ 2nd-round mentors (from Node.js Members)

1. Create an issue in nodejs/members (or another repo) asking for participation as mentors?
1. Follow up on [this comment](https://github.com/nodejs/mentorship/issues/37#issuecomment-396056038)
1. Follow up on [this issue](https://github.com/nodejs/mentorship/issues/32) in which several Node.js Members expressed interest in mentoring

### C. Currently applied mentees

1. ~Should we highlight/sort the mentee list based on (in "the 100" -> timestamp)?~
1. ~Make comments on mentee list to start filtering for good candidates~
1. Reach out to mentees who seem to match current scopes, ask if they want to do beta or wait

### D. Currently applied mentors (**For next round**)

1. Try to get more mentors to join #Mentors slack so we don't have to rely so much on email?
1. 18 emails were sent, 9 bios were made. Follow up with other 9 to try to get their bios up?
1. See if Ben, Stephen, etc. would be interested in a "dry run" of mentoring to provide  early feedback while we work out the details of the 1st official round.
1. Discourage general scope for mentors, provide other options:
    - Mentee under specific-scope mentor 1st round, then mentor specific scope in next round(s)?
    - Help out on the Mentorship Team?
    - Become a TA?
    - Check out Wishlist README and see if there's a more specific scope that fits?

**Comment by detrohutt** [comment]
> Should we highlight/sort the mentee list based on (in "the 100" -> timestamp)?

This seems like a prerequisite/reasonable first step to matching to me. If @nodejs/mentorship thinks this is a good idea I can go ahead and do it. The only issue is I don't see a way to correlate Slack usernames (the list of 100) to emails (the full list of responses). Should we post in #mentorship asking those who made it on the list to PM me their emails or something?

**Comment by Bamieh** [comment]
@detrohutt There is no need for slack usernames at first, we can filter the responses from the form, then those top x numbers in the list will be contacted via email, and it is really easy to figure out their slack usernames from their name afterwards.

**Comment by detrohutt** [comment]
@Bamieh I thought we were prioritizing the first-round mentees based on the "first 100 to confirm in slack" list that @codeekage made/shared? Are we prioritizing based on who filled out the application form first?

**Comment by codeekage** [comment]
@Bamieh do you plan on using registered mentees and first x number from the list to start the first cohort?  Is this because of some validations issues or?

**Comment by j0t3x** [comment]
Hi, I'm an aspiring mentee and applied to the form some weeks ago but wasn't aware of the slack channel until today.

**Comment by Bamieh** [comment]
IMHO i believe our frame of reference should be the form sheet since people explicitly agreed on the CoC there, they have a bio, application dates, github handles, and lots of useful information about them.

It is also not fair to have a race of who is online on slack first to join the first round. People live in different timezones and use slack differently from one another, plus some people like @j0t3x did not get an email about joining slack since they applied after that email was sent, and he deserves an equal opportunity as well.

**Comment by detrohutt** [comment]
@Bamieh I agree with your reasoning. That's also much less work not having to try and cross-reference the two lists. I just misunderstood what was discussed at the meeting it seems. So are we taking the form timestamp into consideration, or are we considering all applied mentees equally?

After some thought, my opinion is that we should either:

1. prioritize the non-collaborator applied mentors as first-round mentees
2. allow less-specific mentoring to be done by non-collaborator mentors, especially if there are mentees who are looking for more generic mentoring (like nodejs/node scope or something?) 
3. find mentees who would like to commit to becoming mentors after graduation, and then prioritize them

If we don't address the problem of not having enough mentors, we're going to have people signing up faster than we can mentor them.

So while I wish we could reward early adopters, it's ultimately in the best interest of everyone to prioritize future mentors instead. If we don't, all but a very small number of mentees are going to have to wait much, much longer than they would otherwise.

**Comment by j0t3x** [comment]
> 3. find mentees who would like to commit to becoming mentors after graduation, and then prioritize them

This one is actually pretty good IMO!

**Comment by ankibalyan** [comment]
@Bamieh sorting out based on form timestamp is fine, and there be couple of thousands who applied with form. but there are many who just left out the program becasue of certain reason. So when you send emails to first x from the form timeline, I'm not even sure if it can be completed with in 10rounds of sending mails and then waiting for replies.
Instead I'd say send emails to everyone that, our mentoring program is going to start very soon, 

Any one of these methods
Please reply to the mail for confirmation.
Fill out form / comment on github from on one particluar day

Incoming confirmation can be sorted based on previous and current timeline.
