### ISSUE TITLE
How to know which team I am assigned to?

### ISSUE THREAD

**Issue by Parikshit-Hooda** [nodejs/mentorship#69]
How do I find out which team/group am I assigned to? I am a mentee but haven't been active with the discussions and meetings because of some personal stuff. Is there any way to catch up in short time?

**Comment by detrohutt** [comment]
Don't worry, there is nothing to catch up on right now. We had to move the start date back. Right now no one is assigned to a team. Just keep an eye on the #mentorship slack channel for updates.

**Comment by Parikshit-Hooda** [comment]
Can I get the link of the slack channel?



Sent from my Redmi 4
On "A.J. Roberts" <notifications@github.com>, 19 Jun 2018 4:36 pm wrote:

Don't worry, there is nothing to catch up on right now. We had to move the start date back. Right now no one is assigned to a team. Just keep an eye on the #mentorship slack channel for updates.

**Comment by detrohutt** [comment]
@Parikshit-Hooda Join https://node-js.slack.com/ and then you'll probably have to search for the #mentorship channel from there.
