### ISSUE TITLE
suggestion: Project for Group visibility 

### ISSUE THREAD

**Issue by kapekost** [nodejs/mentorship#72]
Any ideas on how would the Project functionality be useful between mentor/mentee work?

A flow I can think right now is described below. (Brain storming)

- Mentor or Mentee set up a project with as much info as possible.
- The paired people after having a few sessions, decide on milestones and sub-tasks
- Tickets on the project board with a specific format (link with info/details/PRs/video-sessions or GDocs) 

Mentors and mentees that can contribute to the project can simply reach out and get quickly up to speed

**Comment by Bamieh** [comment]
@kapekost I believe this is awesome but it is mainly dictated by the dynamics between each mentor/mentee and how they prefer to manage their milestones.

Personally I prefer the program to only require the bare minimum, then the mentor/mentee can add their personal implementations to their likings.

The bare minimum in my opinion is to have each pair have an issue to report back to whenever a event happens (meetings, milestones, etc). I also do not favor creating repos for each pair in the nodejs project as it will clutter the orgranization's github, also it will add additional requirements and setup time to start the process.

The reason we need this open issue to track progress (or in PRs) is to make sure everyone has the smoothest experience in both good times and times of conflict. Note that our moderation WG and CoC is built around github, so this requires us to have the source of thruth for everything happening between every pair on reported to `nodejs/mentorship` someway or another.

If i was to mentor I would create a personal repo for me and my mentee with your suggested flow, then link the progress on that repo back to `nodejs/mentorship` by submitting PRs or update the issue. Some might prefer using other tools like trello or notion. Again the program only requires the pair to keep reporting back to this repo.

**Comment by kapekost** [comment]
Indeed 🤔it does sound like getting away from the bare minimum, and something each group can define as they see fit. 

There a difference though to what you mention for the repos, I was referring to a single repo (probably this) where we can create many projects. each project for a group, not personal repos with projects.
I was am not sure from a ticket in a project, it should allow to track commits(+PRs +issues). Just to reduce the noise of issues being used as open projects (in case some projects will get too large)

**Comment by Bamieh** [comment]
@kapekost ahha, does managing a project in the repo requires the users to be members in node?

**Comment by kapekost** [comment]
That sounds like a problem. I havent seen the latest permission stuff, but I suspect there would be a requered step to allow some actions.

**Comment by kapekost** [comment]
yeah.. I think we can close this issue now.. 
https://help.github.com/enterprise/2.13/user/articles/repository-permission-levels-for-an-organization/
If I get this right, the projects are available only for write+ permissions :(

**Comment by detrohutt** [comment]
@kapekost thanks for the update. That does appear to be the case. I like the idea @Bamieh mentioned of mentors optionally doing this on a personal repo. Then for visibility maybe we could have a document like `PROJECTS.md` that mentors can PR to when they have a project that others could contribute to.

That also kind of coincides with the goal of my [wishlist initiative](https://github.com/nodejs/wishlist). Although I haven't gotten it set up yet, it's going to be for directing volunteers to where help is needed. It was originally intended mainly for working groups and initiatives to use, but I could possibly add a section for Mentorship projects. But maybe they're better left in this repo.. something to think about.

Anyway, thanks for the suggestion and feel free to open more issues if you have other ideas.
