### ISSUE TITLE
[Mentor Bio] Dan Shaw

### ISSUE THREAD

**Issue by dshaw** [nodejs/mentorship#74]
Basic info | &nbsp;
-|-
Preferred mentoring format | 1:1
Mentoring scope | Node.js Community Committee (CommComm)
Background | Open Source Exec. Founder @NodeSource, The Node Firm. Always bet on Node.js ✨
Experience | 20+ years

### About me

Hey, everyone. I am Dan Shaw AKA dshaw. I'm an Node.js old-timer and active in the Community Committee and Node.js governance.

I hosted the NodeUp podcast for years. I was a senior engineer at Voxer, one of the first big Node.js companies. I founded the first Node.js consultancy, The Node Firm and founded NodeSource, the Enterprise Node.js company. I cross-over from engineering to business. I have worked as an individual contributor, Lead Engineer, VP of Engineering, and CTO. I have served multiple times as a startup CEO. I am passionate about creating diverse communities of people and helping others succeed.

I am @nodejs/community-committee Member, where I created and champion @nodejs/user-feedback and have helped champion the @nodejs/mentorship team. I'm looking for a mentee who is interested in improving their understanding of the Node.js project and becoming an active contributor to the success of the CommComm. Preferably someone interested in taking on the responsibility of leading an Initiative or Working Group of their own.

**Comment by WaleedAshraf** [comment]
This is great 👍 
But are we going to create an issue for each mentor bio? Maybe we can add a `mentors_bio.md` file and add everyone there.

**Comment by Bamieh** [comment]
@WaleedAshraf we might have to do that in the future, for now this filter over issues is enough: https://github.com/nodejs/mentorship/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Amentor

**Comment by dshaw** [comment]
@WaleedAshraf That’s smart. We do something similar with https://github.com/dshaw/alwaysforward . Shows start as issues and are iterated upon, then later after the show there’re converted into markdown docs.

**Comment by dshaw** [comment]
Matched Mentor/Mentee collaboration would thread well as issues and comments.
