### ISSUE TITLE
Address (or be explicit about not addressing) YouTube chat comments.

### ISSUE THREAD

**Issue by detrohutt** [nodejs/mentorship#76]
![Comments from today's meeting](https://puu.sh/AO8yz/067fdf521f.png)

We had some questions in the YouTube live chat today that went unanswered. I think we should either take a second at the end of meetings to look and see if we've been asked questions or direct viewers to open issues on this repo, join the slack, etc. if they have questions.

**Comment by Bamieh** [comment]
@detrohutt definitely this is something we overlooked! i have reached out for sumant on slack.

**Comment by detrohutt** [comment]
We've added a section to the meeting notes template to remind us about this at each meeting.
