### ISSUE TITLE
Mentorship Program Happening at JS Interactive

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/mentorship#83]
During the last CommComm meeting, I mentioned that we would be holding a speed networking and mentoring session during JS Interactive. Below is a bit more information on this. Please note, that this is not public yet, and will be added to the JS Interactive website on Wednesday (August 1). 

The Linux Foundation did this at KubeCon and it was really well attended. We received positive feedback from both mentee and mentors. 

Please send questions my way, if you have any. 

**Speed Networking and Mentoring Session**

Date: Wednesday, October 10
Time: 4:40-5:40 pm
Location: TBD
**Cost: Complimentary; Pre-registration required.**
 
_We are so pleased to offer, for the first time, a Speed Networking & Mentoring Session at JS Interactive.

The event, taking place on Wednesday, October 10, is designed to attract, nurture and grow the next generation of open source contributors. Open to all, this community event will pair seasoned veterans with anyone hoping to expand their network and gain some valuable insider’s perspective on tech or community._
-----------------------
**Mentees:**
Are you looking to grow your technical skills, join an open-source JavaScript project or tackle a career change? Whether you’re new, or not so new, to open source and JavaScript, we invite you to register to attend the mentoring session.

The session will have two tracks — technical and community — with mentors answering questions in one of these areas and you’ll have the chance to meet with representatives from various open source JavaScript communities. 
-------------------------
**Mentors**
We are looking for mentors from various JavaScript communities within each area -- technical and community -- to join us for the session.

Join this event to give advice to people new, and not so new, to open source. All that’s required is a short prep. call, attending the session and meeting new members in the community. 
--------------------------
**Open to all JS Interactive attendees.**
EVENT DETAILS 
Date: Wednesday, October 10
Time: 4:40-5:40 pm
Location: TBD
Registration Cost: Complimentary; Pre-registration required.
How to Register:
Pre-registration for this session is required. Be sure to sign up soon as spots are limited! Based on your interest, please complete the [MENTOR](https://goo.gl/forms/lKelwGxYy9TWH1UD3) or [MENTEE](https://goo.gl/forms/S8zqGrrqBr0zZ5962) form.

**Comment by codeekage** [comment]
@dshaw @Bamieh @detrohutt

**Comment by dshaw** [comment]
@ZibbyKeaton Awesome. I did this at KubeCon Austin 2017. It was a great experience. The Mentorship Team would love to help with this.  @nodejs/mentorship 

We'd appreciate 2 minutes to introduce Node.js Mentorship team, mentors and mentees. So we can invite folks to the longer presentation at during the Collaborator Summit.

Thank you.

**Comment by ZibbyKeaton** [comment]
@dshaw I would imagine you would want to do this in advance of the conference, so folks that are interested in potentially joining could plan their travel accordingly?
