### ISSUE TITLE
Create processes/guidelines for handling undesirable events during the program

### ISSUE THREAD

**Issue by detrohutt** [nodejs/mentorship#86]

**Comment by dshaw** [comment]
Undesirable events:
* Unresponsive Mentors
  - Especially impactful when mentor has multiple mentees
* Unresponsive Mentees
  - Could impact Mentor retention.

**Comment by dshaw** [comment]
TODO: Request preferred alternative communication channel from Mentors and Mentees.

**Comment by dshaw** [comment]
Proposed "escalation" process

First instance:
* Mentorship team contacts Mentor/Mentee and confirms availability.

Second instance:
* Mentor/Mentee asked to exit the current cohort

Third (consecutive?) instance:
* Mentor/Mentee asked to exit the mentorship program
