### ISSUE TITLE
How to handle mentor/mentee pair deciding to work together after graduation

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#88]
Openning this issue on behalf of @dshaw 

> Discuss How to handle a Mentorship pairing where both wish to continue working together.

**Comment by dshaw** [comment]
NOTE: We shouldn't force Mentors to re-up for a subsequent cohort.

**Comment by dshaw** [comment]
This issue is a Mentorship team concern (having enough Mentor capacity to serve the quantity of Mentees) and we should not impose that concern upon participants.
