### ISSUE TITLE
Comments on B&J Mentorship Diary #87

### ISSUE THREAD

**Issue by profnandaa** [nodejs/mentorship#92]
I was much tempted to comment [here](https://github.com/nodejs/mentorship/issues/87), but I figured a better way might be to open an extra issue for this so that I don't break the flow. Anyone else is welcome to use this issue too.

@Bamieh + @ratracegrad - thank you so much for your notes and recordings, I'm sure a lot of us are going to learn a lot! 👍

**Comment by Bamieh** [comment]
@ProfNandaa Thank you a lot for you kind words. The real thank you should go to @ratracegrad and @bcoe!

**Comment by ratracegrad** [comment]
@ProfNandaa Thanks for the kind words. I am thrilled to be working with @bcoe. I love the chance to share my experience so that it helps others.

**Comment by profnandaa** [comment]
@ratracegrad -- following. On your [previous note](https://github.com/nodejs/mentorship/issues/87#issuecomment-418565840), could you add the link to your PR? I had to [search for it](https://github.com/nodejs/node/pull/22424).
