### ISSUE TITLE
Mentorship Program Administrative Tasks

### ISSUE THREAD

**Issue by detrohutt** [nodejs/mentorship#95]
#### Team Member Roles and Delegation
We still need to decide on some specific roles and start delegating tasks. This will either create more engagement from current members or make it clear if we need to recruit more members.

#### Team Meeting Issue Creation
We haven't had agenda issues for the meetings in a while now. Let's figure out what's blocking us from creating those and try to resolve it.

#### Agenda Items
It seems like we haven't been adequately tracking and creating our agenda items as issues. I've been especially guilty of this one.

#### Action Items
I feel like a lot of our past action items have fallen through the cracks and never completed. We may need to start creating issues for our action items. Alternatively maybe it'd be enough to follow up on action items from the previous meeting notes and roll them over to the current notes if they're not complete.

#### Stale Issues
I think some of our open issues could be closed now.

**Comment by dshaw** [comment]
Check out Node.js CommComm chair time contribution expectations that @bnb shared:
https://github.com/nodejs/community-committee/issues/363#issuecomment-414329262

**Comment by sladyn98** [comment]
@detrohutt Hello, Is this program still open.I applied for a mentee but have not received a reply.

**Comment by ankibalyan** [comment]
@sladyn98 Currently It is running under beta program, if you have applied. You will get notified sooner or later to your mail or mentorship channel in the slack group.

stay tuned to https://node-js.slack.com/messages/C8RND7M5Z

**Comment by sladyn98** [comment]
Can you invite me to the slack channel

**Comment by dshaw** [comment]
@sladyn98 Head to http://nodeslackers.com to get access to the Node.js slack.
