### ISSUE TITLE
Notify attendee about successful registration

### ISSUE THREAD

**Issue by misha-erm** [nodejs/mentorship#97]
Currently it's not visible whether one's registration form was received or no. People easily can forget if they clicked 'send' or something went wrong.
It would be nice to receive confirmation letter that form is awaiting for review or have somewhere status list of attendees

**Comment by Bamieh** [comment]
@MikeYermolayev thanks for the feedback, I completely agree with you. I'll tag this so we can discuss it in the upcoming mentorship meeting.

**Comment by misha-erm** [comment]
I guess, that this closed issue means that nodeJS mentorship is dead, right?

**Comment by davidguttman** [comment]
Not at all! We’re just closing old issues. 

Join the slack mentorship channel for updates on the next round.

**Comment by saulonunesdev** [comment]
@MikeYermolayev  

Join at https://www.nodeslackers.com/

Channel: *mentorship*
